### ISSUE TITLE
Qualita' bassa video

### ISSUE THREAD

**Issue by Testato** [luivit/plugin.video.rivedila7#10]
il sito di LA7 mette a disposizione video a diversa qualita', il plugin pero' usa solo i video a qualita' bassa.
Se non si vuole dare all'utente la possibilita' di selezionare la qualita' credo sia piu' corretto ed utile che il plugin selezionasse il video ad alta qualita'.

Ho verificato la cosa sia sulla funzionalita' RivediLA7 che sulla funzionalita' Tutti i programmi

Basta lanciare sia sul browser che sul plugin lo stesso video e si nota ad occhio la differenza
http://www.la7.it/dimartedi/rivedila7/dimarted%C3%AC-puntata-12122017-13-12-2017-229606

**Comment by luivit** [comment]
mhm, il link .mp4 è solo uno nel codice della pagina. Forse è uno streaming adattivo.
Controllerò meglio asap

**Comment by Testato** [comment]
Se dai in pasto il link a Jdownloader vedi che vengono fuori due video, se vuoi posso postarti screenshot

**Comment by Testato** [comment]
questi sono i video che intercetta Jdownload sul link che ho messo sopra, come vedi c'e' il 244p ed il 576p

![screenshot from 2017-12-16 10-18-09](https://user-images.githubusercontent.com/6893841/34069165-df4967ae-e24a-11e7-8ec1-5ded28d6fa42.png)

**Comment by luivit** [comment]
da kodi 17+ verrà utilizzato automaticamente lo stream migliore in base alla velocità di internet, come avviene sul sito.

**Comment by Testato** [comment]
mi sa che questo e' da riaprire :-)

Ho fatto dei test e la differenza di qualita' resta, questo ad esempio e' la differenza sull'ultimo rpomramma sezione Replay disponibile in questo momento, Otto e Mezzo, a sinistra c'e' il video Kodi ed a destra il video sul sito web.
E' palese la differenza guardando il testo

![screenshot from 2017-12-22 22-42-58](https://user-images.githubusercontent.com/6893841/34313196-ca740284-e769-11e7-805b-e95f8a64fb34.png)

**Comment by luivit** [comment]
Alcuni programmi hanno nella playlist solo stream 244p (per esempio tgla7 presi dai vari giorni di trasmissione). Cmq dopo do un ulteriore sguardo

**Comment by Testato** [comment]
Logicamente il test che ho fatto, da cui deriva l'immagine che vedi, è sullo stesso programma, quindi che entrambi siano 244 o 576 poco importa.
È proprio una differenza dovuta a come poi Kodi presenta il video rispetto a Chrome.
La issue è risolta perché premendo "o" si può verificare che il flusso è quello più alto disponibile su quel programma, pero' non mi spiego tale differenza. Tieni aperto contemporaneamente sullo stesso programma Kofi e Chrome e vedrai.

Per la diretta TV invece sicuro esiste solo il 244p ?
Non ho trovato un modo per verificarlo con certezza.

Hai fatto un lavoro eccezionale, manca l'ultima modifica, quella di /programmi e poi si può pubblicare la 1.0 sul repo Kodi secondo me :-)

**Comment by luivit** [comment]
no, lo stream live è disponibile in entrambe le versioni. I video del tgla7 hanno unico stream a 244p (video presi fai vari giorni di trasmissione).
Qualunque fa riferimento ad una concatenazione di file .ts (che dovrebbero essere mpeg2, forse sono interlacciati anche) quindi FORSE kodi usa una tecnica di de-interlacciamento diverso dal browser.

**Comment by Testato** [comment]
ma lo stream live io non l'ho mai visto a piu' di 360p, tu dici che lo vedi a 576p ?

![capture](https://user-images.githubusercontent.com/6893841/34321104-8e702576-e807-11e7-908b-5f426d8112a1.JPG)
