### ISSUE TITLE
Diretta tv not working on Openelec

### ISSUE THREAD

**Issue by sowdust** [luivit/plugin.video.rivedila7#12]
On Openelec the live streaming is not working.
From the logs, one can see that the error is a 403 forbidden error from akamai servers.
It might be an issue of cookies or - more probably - missing parameters in the URL request.
I have not had the time to look into it more thoroughly.

**Comment by Testato** [comment]
I'm on openelec and in this moment viewing the live streaming.

Tty to update the plugin from master, and/or try to update Libreelec itself

**Comment by Testato** [comment]
On LibreElec it's ok
Maybe is an OpenElec problem ?
Are you tried the last master version of the plugin ? It is updated yerstaeday also for a better video quality

**Comment by luivit** [comment]
What do you version of kodi use?
You are in Italy? Meaby there is geoblocking

**Comment by sowdust** [comment]
I am very sorry I have forgot to reply. I meant to look deeper into the issue but did not have the time.
I am still experiencing the problem. 
My system is Openelec 7.0.1 (Kodi 16.1)
I am in Italy and I can see the live streaming from the same IP just fine with a regular browser.
To make sure I do not have the wrong version or repository I reinstalled from a zip file created directly from github's button - no difference.
Again, the logs signal a 403 forbidden error against akamai's server.

**Comment by sowdust** [comment]
Some weird update. 
It **might** be an issue on how  xmbc player treats http headers. Coupled with an issue on how Openelec treats proxy settings.
Enabling debug log, I could see, together with the "403 - Forbidden" status codes, an error about a missing CRLF after HTTP headers (which were NOT set in the request).
After trying to reproduce the issue on my pc with no luck, I thougth of setting my laptop as a proxy in Openelec: magically the live video started working - but no data was coming into my pc set up as a proxy.
I also tried setting a non-existent ip on my subnet as proxy : it still works!
So I guess the real bugs are somewhere else - but I'd need more investigation to confirm this hypotesis. Meanwhile, to anybody having the same problem, just set up a fake proxy! ;D

[Italiano] Ho visto solo ora che tutte le issue erano in italiano, in effetti ha senso essendo un'estensione che é molto probabilmente usata solo da chi capisce la nostra lingua :D 
Ho deciso peró di scrivere anche l'ultimo messaggio in inglese in caso possa essere utile a qualcuno che abbia lo stesso problema su altre estensioni.

**Comment by sowdust** [comment]
confermo che con LibreELEC il problema non sussiste
