### ISSUE TITLE
Programmi senza video

### ISSUE THREAD

**Issue by Testato** [luivit/plugin.video.rivedila7#13]
Ormai sono tanti i programmi dove non ci sono  video. Vengono elencati in /tutti-i-programmi ma non hanno video.
Visto che parliamo del 90% dei programmi (esempio nella lettera A solo Atlantide contiene video) proporrei di fare un check sulla presenza o meno di almeno un video e solo dopo far apparire il relativo programma in elenco.
Cosa ne pensi ?

**Comment by luivit** [comment]
il controllo già viene effettuato e se non ci sono video disponibili viene lanciato un messaggio. Controllare prima tutte le voci di una lettera, secondo me, è controproducente. Bisognerebbe fare tot richieste (corrispondenti al numero di programmi) prima di visualizzare la lista, rallentando il tutto. Credo  che sia meglio così,

**Comment by Testato** [comment]
Ok
