### ISSUE TITLE
Diretta live non più funzionante

### ISSUE THREAD

**Issue by lorenzos** [luivit/plugin.video.rivedila7#16]
C'è qualcosa che non va con la diretta Live. Il resto funziona come al solito. Sull'app ufficiale per Android è tutto in regola.

Di seguito le righe di log stampate da Kodi 17.6 (OSMC) quando si prova ad avviare la diretta. Sulla UI compare solo un generico messaggio di errore.

```
19:16:19.016 T:1925888512  NOTICE: VideoPlayer: Opening: ht
p://la7livehls-lh.akamaihd.net/i/livebkup_1@372883/master.m
u8?hdnts=st=1533662019~exp=1533662469~acl=/*~hmac=d7fbfadcd
4ca8004004f5fdbe8df74dc63612ea9a43245db324ff4878d4d1ab
19:16:19.017 T:1925888512 WARNING: CDVDMessageQueue(player)
:Put MSGQ_NOT_INITIALIZED
19:16:19.064 T:1261433600  NOTICE: Creating InputStream
19:16:19.191 T:1261433600  NOTICE: Creating Demuxer
19:16:19.404 T:1261433600   ERROR: OpenDemuxStream - Error
reating demuxer
19:16:19.405 T:1261433600  NOTICE: CVideoPlayer::OnExit()
19:16:19.406 T:1925888512   ERROR: Playlist Player: skippin
 unplayable item: 0, path [plugin://plugin.video.rivedila7/
mode=diretta_live]
19:16:19.407 T:1925888512  NOTICE: CVideoPlayer::CloseFile(
19:16:19.407 T:1925888512  NOTICE: VideoPlayer: waiting for
threads to exit
19:16:19.407 T:1925888512  NOTICE: VideoPlayer: finished wa
ting
19:16:19.408 T:1925888512  NOTICE: CVideoPlayer::CloseFile(
19:16:19.408 T:1925888512  NOTICE: VideoPlayer: waiting for
threads to exit
19:16:19.409 T:1925888512  NOTICE: VideoPlayer: finished wa
ting
19:16:19.415 T:1425511168 WARNING: Attempt to use invalid h
ndle 27
```

**Comment by lorenzos** [comment]
Sì, intendevo l'app TGLa7. Ho scoperto con piacevole sorpresa che il tasto per la diretta comunque tutto il giorno.

**Comment by Testato** [comment]
sto facendo dei test.
Ho notato che rpovando molte volte, 20/30 volte anche, poi improvvisamnete funziona.
Provato sia su Win10 che su Android.

Puoi confermare ?

**Comment by Testato** [comment]
questo il log, con e senza errore

https://paste.ubuntu.com/p/KZFx2WnQfP/

**Comment by lorenzos** [comment]
Ora parte anche a me. Direi il 100% delle volte 🤷‍♂️

**Comment by Testato** [comment]
qui davanti a me non funziona :-)

**Comment by Testato** [comment]
ho scoperto che su Kodi16 funziona.
brutta storia, e' vero che probabilmente La7 ha cambiato modalita' di streaming, ma il funzionamento corretto su Kodi16 dimostra che non e' colpa del plugin.

Probabilmente un bug in Kodi su questo nuovo tipo di streaming ?

Ho aperto richiesta di supporto
https://forum.kodi.tv/showthread.php?tid=334441

**Comment by lorenzos** [comment]
Mmm, in realtà io sono su Kodi 17.6...

**Comment by Testato** [comment]
e ti continua a funzionare ?
puoi provare sia su android che su pc, e con connessioni diverse wifi + cellulare ?
non so che pensare
a me solo su kodi16 va, sul 17.6, l'attuale stable, niente e su nessun so e con nessuna connessione
(dico di testare anche la connessione perche' il sistema di autenticazione di akamai puo' tener conto dell'IP, anche se dai log non sembra che nel nostro caso venga fatto)

**Comment by lorenzos** [comment]
Ho riprovato appena ora. È partito due o tre volte di fila senza problemi, su PC (in realtà un Raspberry con OSMC), quindi ho provato su Android, errore più volte, disattivo il WiFi, ancora errore, riprovo su PC, ora non parte più neanche lì. Ho paura sia molto random :(

**Comment by Testato** [comment]
yep, random, e secondo me non e' un problema del plugin :-(

**Comment by lorenzos** [comment]
Infatti, a questo punto potrebbe essere anche stato un caso che sull'app ufficiale, in quel preciso momento, funzionasse. Continuerò a fare prove quando mi capita, nel frattempo se vuoi chiudere qui fai pure.

**Comment by sowdust** [comment]
usando un proxy ho notato che su libreelec quando richiede il file master.m3u8 da akamai (il primo), fa prima una richiesta HEAD che fallisce per errore 405 "Method not allowed", e poi la regolare richiesta GET, che riceve un 200 ok. A quel punto peró ripete lo stesso procedimento per lo stesso file master.m3u8, fino a che non riceve un 206 "incomplete content".

Dai log si vede che la prima richiesta GET a master.m3u8 ha successo, infatti riesce a prendere il mime/type dalla risposta:
``
DEBUG: CCurlFile::GetMimeType - http://la7livehls-lh.akamaihd.net/i/livebkup_1@372883/master.m3u8?hdnts=st=... -> application/vnd.apple.mpegurl
``

Peró poi, poco dopo, ho un errore 404:
``
22:23:37.134 T:1326441376    INFO: ffmpeg[4F0FE3A0]: [hls,applehttp] Opening 'http://la7livehls-lh.akamaihd.net/i/livebkup_1@372883/index_2_av-b.m3u8?sd=10&rebase=on' for reading
22:23:37.246 T:1326441376   DEBUG: ffmpeg[4F0FE3A0]: [http] HTTP error 404 Not Found
22:23:37.248 T:1326441376   DEBUG: Error, could not open file http://la7livehls-lh.akamaihd.net/i/livebkup_1@372883/master.m3u8?hdnts=st=...
``

Dal browser invece, dove tutto funziona, il flusso é una prima richiesta GET a master.m3u8 e poi le successive richieste ai vari index_2_av-b.m3u8.

**Comment by Testato** [comment]
visto che su kodi16.1 funziona sempre puoi fare un confronto sul tuo proxy per vedere se kodi16 fa richieste diverse ?
Magari ci e' utile per capire.

Ho pensato anche ad un bug di ffmpeg, ma usando mvp, un player linux che usa ffmpeg, non ho rpoblemi a far partire il video inserendo il solo indirizzo.

**Comment by sowdust** [comment]
Credo di aver risolto seguendo i consigli di enen92 in risposta al thread aperto da Testato sul forum. In sostanza bastava aggiungere le indicazioni per l'adaptive streaming. Nel forum si diceva essere anche necessario abilitare il supporto dell'addon "input adaptive", ma in libreelec risultava giá abilitato.
Ho inviato una pull request con le modifiche.

**Comment by Testato** [comment]
Grazie mille, approvo subito la PR.

Comunque il vero bug é quindi in ffmpeg, domani apro una issue.
Perché come dice enen kodi ha deciso di demandare a ffmpeg questo lavoro, eliminando da kodi 17 la gestione di queste cose.

Magari in futuro si potrà tornare all'attuale codice lasciando tutto in mano ad ffmpeg

**Comment by Testato** [comment]
Ok su android non é attivo il plugin adaptive. Abilitandolo manualmente funziona.
Domani vedo se si può abilitare automaticamente via plugin

**Comment by Testato** [comment]
Implementata attivazione automatica dell'add-on InputStream Adaptive.

@luivit 
ho portato la release a 1.8.0 e' venuta l'ora di fare un update del repo Kodi altrimenti non hanno piu' il Live funzionante

**Comment by fatshotty** [comment]
ciao, 
scrivo qui perche' le dirette live non funzionano nuovamente.
Ho provato su Ubuntu18 e LibreElec, entrambi con kodi18.

L'errore e' sempre lo stesso:
`Open - error probing input format, http://m.cortesia.tim.it/
2019-05-14 16:54:41.549 T:1626858352   ERROR: OpenDemuxStream - Error creating demuxer`

grazie in anticipo
