### ISSUE TITLE
Su FireTV non funziona

### ISSUE THREAD

**Issue by Testato** [luivit/plugin.video.rivedila7#18]
Ciao la nuova addon non funziona, mentre avevo installato una vecchia versione 1.0 su un altro fire Tv e funziona benissimo. Please help, grazie in anticipo

_Originally posted by @giofish in https://github.com/luivit/plugin.video.rivedila7/pull/14#issuecomment-432247879_

**Comment by Testato** [comment]
@giofish

non abbiamo una FireTV per testare il problema.

Tu hai fatto l'upgrade auomatico alla nuova versione ?
Prova:
- disinstallare del tutto il plugin
- spegnere e riaccendere la FireTV
- installare dinuovo il plugin
- spegnere riaccendere la FireTV
- provare se funziona

**Comment by giofish** [comment]
Ho seguito le istruzioni ma non funziona.

Una cosa strana e’ se provo a selezionare Live Streaming mi compare una finestra con due opzioni una di “ Resume from 47:33” oppure “Start from beginning”

Grazie mille

On Oct 24, 2018, at 3:45 AM, Testato <notifications@github.com<mailto:notifications@github.com>> wrote:


@giofish<https://github.com/giofish>

non abbiamo una FireTV per testare il problema.

Tu hai fatto l'upgrade auomatico alla nuova versione ?
Prova:

  *   disinstallare del tutto il plugin
  *   spegnere e riaccendere la FireTV
  *   installare dinuovo il plugin
  *   spegnere riaccendere la FireTV
  *   provare se funziona

**Comment by Testato** [comment]
Ma la FireTV che so usa ?
Android ?
Che versione di Kodi Usa ?
fa un po' di screenshot delle varie versioni, di pagine utili a capire, e poi e' importante vedere un logfile epr capire che succede.

Guarda un po' su internet come creare un logfile di Kodi e postalo su pastebin e poi ci dai il link

**Comment by giofish** [comment]
Fire TV uses Fire OS, which is based on Android.
Kodi 17.3
https://paste.kodi.tv/kaxozadizo

Questa e' foto della versione che funziona:
![0a5e07a4-8b8a-49e9-addd-f38eaa32acfc](https://user-images.githubusercontent.com/3314349/47463200-86791480-d7b3-11e8-80e9-7049dd031a50.jpg)

Questa versione non funziona
![6e56f3a4-95ab-4291-afa2-7313acd5ffd7](https://user-images.githubusercontent.com/3314349/47463204-88db6e80-d7b3-11e8-913f-dee9dda89c59.jpg)

**Comment by giofish** [comment]
Questo logfile di Kodi della versione 1.0.0 che funziona, se dovesse servire per confrontare
https://paste.kodi.tv/movetalelo

**Comment by Testato** [comment]
Grazie dei log,
ma solo la diretta non funziona o anche le altre funzioni ?

Dal log sembra che non si attivi inputstream, che è il nuovo sistema che usiamo sulla nuova versione.
ERROR: AddOnLog: InputStream Adaptive: Invalid / not given inputstream.adaptive.manifest_type

Controlla se è presente ed attivo, può essere che su FireTv non è presente di default e puoi installarlo e attivarlo manualmente.
Se è così poi possiamo vedere come automatizzare la cosa

https://seo-michael.co.uk/how-to-enable-rtmp-input-inputstream-adaptive-kodi/

**Comment by giofish** [comment]
Prego,

ho completamente fatto un restore di tutto e installato solo RivediLa7 addon e funziona tutto :)
Probabilmente interferiva con altre add ons, che installerò una alla volta per testare.

Grazie mille e in caso di problemi ti faro’ sapere.


On Nov 1, 2018, at 12:24 PM, Testato <notifications@github.com<mailto:notifications@github.com>> wrote:


Grazie dei log,
ma solo la diretta non funziona o anche le altre funzioni ?

Dal log sembra che non si attivi inputstream, che è il nuovo sistema che usiamo sulla nuova versione.
ERROR: AddOnLog: InputStream Adaptive: Invalid / not given inputstream.adaptive.manifest_type

Controlla se è presente ed attivo, può essere che su FireTv non è presente di default e puoi installarlo e attivarlo manualmente.
Se è così poi possiamo vedere come automatizzare la cosa

https://seo-michael.co.uk/how-to-enable-rtmp-input-inputstream-adaptive-kodi/

**Comment by Testato** [comment]
Può essere che c'è un altro addon che blocca inputstreamer.
Controlla comunque manualmente come è la situazione, ti servirà per capire se un altro add on lo disattiva
