### ISSUE TITLE
la7 nuovo sito

### ISSUE THREAD

**Issue by lpuglia** [luivit/plugin.video.rivedila7#20]
Salve, pare che l'interfaccia del sito di LA7 sia completamente cambiata, suppongo che questo sia il motivo per cui il plugin non funziona più.

**Comment by Testato** [comment]
Confermato :-)

Se siamo fortunati bastano pochi ritocchi, sembra a prima vista (dal cellulare al volo) solo un rimaneggiamento grafico.

Per fortuna o sfortuna sono in vacanza e quindi ci posso mettere mano a fine mese :-)

Se qualcuno fa delle prove scrivete qui i risultati

**Comment by sowdust** [comment]
Ho avuto pochissimo tempo, ma intanto ho fatto una pull request che dovrebbe far funzionare la diretta live. Hanno cambiato il formato dell'url (non ha piu' il protocollo, comincia con //) - in quel caso ci ho semplicemente aggiunto 'https:' davanti. Tra l'altro cosí com'é il nuovo sito non mi funziona la diretta neppure su Firefox...

**Comment by Testato** [comment]
Ok, mergiato.
Al momento quindi funziona solo la Diretta e il Tg-La7d

**Comment by lorenzos** [comment]
> Tra l'altro cosí com'é il nuovo sito non mi funziona la diretta neppure su Firefox...

@sowdust L'ho notato anch'io ieri. Ho provato a disattivare uBlock, ma niente, mi funziona solo su Chromium (sono su Linux). Hai per caso capito il perché?

**Comment by lpuglia** [comment]
> > Tra l'altro cosí com'é il nuovo sito non mi funziona la diretta neppure su Firefox...
> 
> @sowdust L'ho notato anch'io ieri. Ho provato a disattivare uBlock, ma niente, mi funziona solo su Chromium (sono su Linux). Hai per caso capito il perché?

Su Firefox+Windows funziona, deve essere sicuramente qualche problema con il DRM che non hanno testato su linux...

**Comment by lorenzos** [comment]
> > > Tra l'altro cosí com'é il nuovo sito non mi funziona la diretta neppure su Firefox...
> > 
> > 
> > @sowdust L'ho notato anch'io ieri. Ho provato a disattivare uBlock, ma niente, mi funziona solo su Chromium (sono su Linux). Hai per caso capito il perché?
> 
> Su Firefox+Windows funziona, deve essere sicuramente qualche problema con il DRM:
> https://itsfoss.com/netflix-firefox-linux/

No, il DRM è abilitato, ho controllato. È tutto a posto, tranne una valanga di warning in console insieme  ad altre cose che sembrano rimasugli di test e debugging... Ho come l'impressione che sia stato fatto coi piedi il sito nuovo...

**Comment by Testato** [comment]
Sarà lo stesso sviluppatore del vecchio :-)

**Comment by Testato** [comment]
Ho sistemato tutte le funzionalita', mi resta da sistemare solo la sezione Programmi on demand e poi vorrei aggiungere la nuova funzione Teche.
Poi rilasciamo la Rel 3.0 :-)

**Comment by Testato** [comment]
stanotte hanno ricambiato il link della Diretta, ho gia' risistemato sulla nuova versione.
Ho aggiunto la sezione Teche ed ho aggiunto lo scraping dei programmi la7D.

Oggi faccio una modifica ad hoc per le puntate di Atlantide e poi pubblico la nuova versione

**Comment by Testato** [comment]
ok pubblicata la nuova versione 3.0.0 con in aggiunta tanti nuovi programmi OnDemand e la nuova sezione Teche La7

**Comment by lorenzos** [comment]
Ma sui repo ufficiali di Kodi non viene più pubblicato, o sono io che ho problemi sulla mia installazione? È ormai un annetto che scarico da qui, direttamente da GitHub, perché spesso mi serve avere l'ultimo fix nell'ultimo commit, e perciò noto solo ora che la UI di Kodi mi propone la 1.8.0 come ultimo aggiornamento...

**Comment by bitbooster** [comment]
In effetti il repo ufficiale sembra avere ancora the 1.8.0 (sia per Kodi 18/Leia che 17/Krypton)
http://mirrors.kodi.tv/addons/leia/plugin.video.rivedila7/

**Comment by Testato** [comment]
Questa è colpa di @luivit :-)
