### ISSUE TITLE
Come scarico la versione 3.0 da github?

### ISSUE THREAD

**Issue by jackpallet** [luivit/plugin.video.rivedila7#23]
Come da titolo, non ho capito dove sta il link del file .zip da scaricare e aggiungere poi a kodi visto che la nuova versione del plugin non è presente su nessuna repo

**Comment by Testato** [comment]
In alto a destra, hai in verde scarica .zip (se sei su smartphone devi settare il browser come Sito Desktop)

Poi installi il .zip direttamente da kodi

**Comment by Testato** [comment]
Plugin ora presente sul repo Ufficiale Kodi, sia sul 17 che 18
