### ISSUE TITLE
Diretta Live non più funzionante (dicembre 2019)

### ISSUE THREAD

**Issue by lorenzos** [luivit/plugin.video.rivedila7#26]
La Diretta Live non funziona più dall'altro ieri, compare un messaggio "Impossibile visualizzare questo programma". Non so cosa possa essere cambiato sul sito. Nel log appare un'unica riga:

    2019-12-04 19:39:35.095 T:1280791264  NOTICE: NO VIDEO LINK

Grazie mille.

**Comment by Testato** [comment]
Sul mio altro plugin  https://github.com/Testato/RepubblicaItaliana funziona.
Lì uso il link diretto allo stream, quindi vuol dire che hanno cambiato la pagina.
Potremmo anche qui inserire il link diretto invece di scrappare la pagina, tanto sono più le volte che cambiano la pagina che quelle che cambiano il link allo stream.

@luivit cosa ne pensi ?

**Comment by lorenzos** [comment]
In realtà mi pare che l'altro plugin avvii per qualche motivo una registrazione di un programma di stamattina, invece che la diretta... Può significare qualcosa?

**Comment by pdpcrew** [comment]
Ciao. Il link diretto usato nell'altro plugin [1] rimanda ad un video di 1 minuto che gira in loop. Se uso direttamente il link preso dalla pagina di la7 diretta live [2], mi da questo errore:
`AddOnLog: InputStream Adaptive: Unsupported encryption method`
Il codice della pagina di la7 è questo:
```
drmSupport: true,
  src:{
  m3u8:
  'https://d15umi5iaezxgx.cloudfront.net/OUT/HLS/Live.m3u8',
  dash:
  'https://d15umi5iaezxgx.cloudfront.net/OUT/DASH/Live.mpd'
  }
```
Purtroppo non ne so abbastanza di video streaming per dare altre informazioni utili.

[1] https://stream.la7.it/out/v1/fe849af8150c4c51889b15dadc717774/index.m3u8
[2] https://d15umi5iaezxgx.cloudfront.net/OUT/HLS/Live.m3u8

**Comment by Testato** [comment]
?
Avete confrontato la diretta dell'altro plugin con una TV ?

**Comment by Testato** [comment]
@pdpcrew 
Non usarlo manualmente, installa l'altro plugin e provalo

**Comment by pdpcrew** [comment]
@Testato certo, per prima cosa ho installato l'altro plug-in e provato la diretta. A me ritorna sempre lo stesso video.

Io uso Kodi18.2 su LibreElec 9.0.2 installato su una x86 board collegata alla TV.

**Comment by Testato** [comment]
Ok, allora ho due plugin da sistemare 😅
Sono negli Stati Uniti al momento, però oggi pomeriggio vedo di trovare un attimo per sistemarli entrambi.
Grazie dei test

**Comment by Testato** [comment]
raga qualcuno di voi ha un iphone ?
Se è vero cio' che penso di aver trovato sugli iPhone non dovrebbe funzionare la diretta via browser, cioe' direttamente su https://www.la7.it/dirette-tv
Ma mi sembra una cosa assurda, puo' essere che abbiano fatto un tale errore ?
Se avete la possibilita datemi conferma

**Comment by Testato** [comment]
Merda, è confermato :-)
Allora ora dobbiamo solo aspettare che gli aifonisti si facciano sentire e fanno sistemare la cosa

**Comment by lorenzos** [comment]
Cosa hai "trovato"? C'è un problema che renderebbe lo stream impossibile su iPhone come su Kodi?

**Comment by sowdust** [comment]
su iPhone con Safari lo streaming si vede correttamente. Non ho avuto ancora tempo di guardarci bene, ma ad una prima occhiata all'HTML di /dirette-tv mi pare abbiano 1) cambiato completamente la struttura dei link (la regex non funziona più) e 2) implementato il supporto per il DRM

**Comment by lorenzos** [comment]
@sowdust Il DRM credo sia implementato da mesi ormai, ricordo che su Firefox su Ubuntu non funzionasse per questo motivo (almeno inizialmente). Spero che il fatto che su iPhone funzioni sia una buona notizia @Testato

**Comment by Testato** [comment]
@sowdust 
Si la regex l'ho sistemata, ma il problema è un altro.
Ora loro hanno due stream nella pagina, un .m3u8 e eventualmente un .mpd
Il .m3u8 è sbagliato, non contiene i link allo stream, quindi non funziona su nessun sistema operativo e visto che noi usiamo m3u8 non funziona nemmeno sul nostro plugin.
Android bypassa il problema perché automaticamente usa il .mpd, mentre iphone non è compatibile con .mpd
Almeno questa è la mia ipotesi, ed ho provato con chrome su un iphone e mi fa vedere solo le pubblicità.
Hai aspettato che finissero le pubblicità ?
Puoi provare anche con Chrome invece di Safari sempre dopo le pubblicità ?

Questa cosa di provare su iphone mi è venuta in mente proprio per confermare la mia tesi che il .m3u8 sia realmente guasto, Visto che ho letto che con .mdp mi aspetto che anche a te non funzioni.

Certo che se non si sono accorti che in un sol colpo hanno perso tutti gli utenti Apple è una cosa assurda :-)

**Comment by sowdust** [comment]
Si', ho aspettato il termine della pubblicita' ;) con Brave non funziona, ma potrebbe essere anche per altri motivi.
In effetti aprendo lo stream m3u8 con vlc anche quello si lamenta dando errori (httplive stream error: #EXT-X-VERSION should be version 1, 2 or 3 iso 5 - es demux error: cannot peek), anche se non apre nemmeno l'mpd (senza dare errori). Purtroppo non ho tempo di approfondire molto, spero di poterci guardare meglio nei prossimi giorni!

**Comment by Testato** [comment]
Semplicemente il .m3u8 non contiene link quindi c'è niente da fare.
Se la situazione perdura vediamo di modificare il plugin al fine di legge il .mpd
Ma vorrei evitarlo visto che tutti gli altri contenuti sono su .m3u8

Probabilmente hanno implementato in Safari la compatibilità con .mpd e per questo su safari funziona

**Comment by Derewith** [comment]
currentSrc cambia se si usa Chrome il player riprodurrà il file .mpd 
se si usa Safari riproduce il file .m3u8 . 

Per quanto io abbia indagato, 
bisogna decriptare correttamente il videoLa7 module...

**Comment by Testato** [comment]
E perché nemmeno con Chrome funziona il .m3u8 ?
Concordi che il m3u8 è guasto ?
Guarda internamente, non ci sono i link

**Comment by Testato** [comment]
Ma su chrome anche se uso l'agent di Safari continua a non funzionare.
Sei sicuro che su safari stai leggendo m3u8 ?
Cioè può essere che siano anche passati a DRM (il che vuol dire mettere in gioco widivine probabilmente) ma prima vorrei capire come mai nel .m3u8 non trovo link allo stream

**Comment by sowdust** [comment]
ho dato una veloce occhiata questa mattina. pare che il problema sia causato dal DRM.
L'm3u8 implementa SAMPLE-AES come cifratura; l'unico metodo che, stando alla  [wiki di inputstream.adaptive](https://github.com/peak3d/inputstream.adaptive/wiki/Playing-multi-bitrate-stream-from-a-python-addon) non é supportato.
L'mpd invece necessita com.microsoft.playready  che é supportato solo su device Android (sempre da wiki).
Ma spero di sbagliarmi!

**Comment by Testato** [comment]
@sowdust 
Ma lamia domanda resta, dive trovi il link allo stream se l'm3u8 risulta vuoto ?
A te non risulta vuoto ?
Posta il link diretto allo stream che hai trovato

**Comment by sowdust** [comment]
@Testato no, non mi pare vuoto:
da /OUT/HLS/Live.m3u8 ti ricavi ad esempio /OUT/HLS/Live_960x540_.m3u8, che contiene l'indicazione sul metodo di cifratura usato:
`#EXT-X-KEY:METHOD=SAMPLE-AES,URI="skd [...]`
E da qui hai i link ai vari chunk cifrati (nella forma /OUT/HLS/Live_960x540_20191229T150657_1858628.ts)

**Comment by matteomartelli** [comment]
Confermo anche io lo stesso problema con la diretta live.
La7-La7d addon 3.1.1
Libreelec 9.0
Kodi 18.0-BETA2

Inoltre se può essere utile di recente non riesco più a vedere la diretta neanche da Firefox 68.4.1 su Android 9. La riproduzione fallisce con il seguente errore:
`DRM: KeySystem Access Denied! -- Key system access denied! EME has been preffed off`

Sembrerebbe confermare che il problema è causato da un loro cambio di gestione del DRM.

**Comment by Testato** [comment]
@sowdust 
ok ho visto i link nei .m3u8.
Ho chiesto info qui, magari lo stanno implementando Sample-Aes
https://github.com/peak3d/inputstream.adaptive/issues/96

**Comment by Testato** [comment]
Ci sono vicino :-)
      
<ContentProtection cenc:default_KID="DB057321-C922-4C25-A7CC-D75D911DD1FC" schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed">
        <cenc:pssh xmlns:cenc="urn:mpeg:cenc:2013">AAAAYXBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAAEEIARIQ2wVzIckiTCWnzNddkR3R/BoFQ29uYXgiJDhmOTVkNDBhLTc3ZmItNDYwMC04ZjU4LTA4ZmU4ODM3NmEzOQ==</cenc:pssh>
      </ContentProtection>

**Comment by Testato** [comment]
sembra che il server per la chiave di decriptazione sia questo
`https://la7.prod.conax.cloud/widevine/license?d=1580401136927`
ma il valore di d= non so da dove esce e cambia in continuazione, quindi il server non risponde con la key :-(

**Comment by meden** [comment]
Credo sia il timestamp (con i millisecondi) e credo venga generato via Javascript. Avevo dato un'occhiata ai sorgenti, mi pareva di aver visto qualcosa di simile.

In effetti il valore 1580401136(927) [corrisponde a Thu Jan 30 16:18:56 2020 UTC](https://duckduckgo.com/?q=unixtime+1580401136).

**Comment by lorenzos** [comment]
> `1580401136927`

È un timestamp Unix in millisecondi, corrisponde a 01/30/2020 @ 4:18pm (UTC).

Probabilmente va dato aggiornato per ricevere una chiave valida?

**Comment by Testato** [comment]
ottimo, ci provo, bella intuizione grazie
Nel frattempo ho aperto una issue apposita a IA 
https://github.com/peak3d/inputstream.adaptive/issues/381

**Comment by meden** [comment]
Aggiungo qualche altro dettaglio emerso dal mio tentativo di risolvere il problema:
* L'uso del descrittore DASH è possibile e la modifica è banale (basta cambiare la regexp).
* Stando al changelog, Inputstream.adaptive supporta DASH
* DASH però non è disponibile su tutte le piattaforme (nel mio caso, Android, lo è)
* Anche se strano, mentre i flussi nel m3u8 usano Widevine, quelli nel mpd usano MS PlayReady (anche questo schema DRM è supportato dalla mia box Android)
* Kodi sembra seguire correttamente tutte le redirezioni, però la riproduzione fallisce a causa di errori
* Gli errori di riproduzione sono in effetti frequenti anche con il browser, tanto in Android quanto in Linux. Sembra che i server delle chiavi diano spesso problemi, con errori o timeout (il che spiegherebbe i fallimenti di Inputstream.adaptive).

Questo è quello che credo accada, anche se non ho fatto un'analisi estremamente approfondita, perciò non posso essere sicuro dei veri motivi per cui Lodi fallisce sempre nel riprodurre un flusso che sulla carta è supportato.

**Comment by Testato** [comment]
### Changelog
4.0.0 (2020-02-01) - Brexit Edition
- Fixed LA7 Live (implemented Widevine DRM)
- Added LA7d Live
- Use of InputstreamHelper for Inputstream Adaptive and Widevine management
