### ISSUE TITLE
Diretta di La7 in php

### ISSUE THREAD

**Issue by ilariafabiano** [luivit/plugin.video.rivedila7#28]
Sto cercando di convertire la funzione play_dirette(url) in php recentemente aggiornata da @Testato, ma sto riscontrando dei problemi. Qualcuno puoi aiutarmi?

**Comment by Testato** [comment]
A qual pro ?

**Comment by ilariafabiano** [comment]
Offrire la diretta di La7 a chi non utilizza Kodi

**Comment by Testato** [comment]
Hai un sito di tv in streaming ? Link ?

**Comment by ilariafabiano** [comment]
Non ho un sito di TV in streaming ma un applicazione su App Store

**Comment by luivit** [comment]
> Non ho un sito di TV in streaming ma un applicazione su App Store

Per PHP Devi vedere ffmpeg con openSsl, per creare uno stream AES HLS

**Comment by ilariafabiano** [comment]
Correggetemi se sbaglio, il preTokenUrl viene utilizzato nel header preAuthorization per accedere a license_url giusto?

**Comment by Testato** [comment]
Hls della diretta é criptato con il drm apple, poi funzionerebbe solo su
apple.

Il Mer 5 Feb 2020, 13:52 luivit <notifications@github.com> ha scritto:

**Comment by ilariafabiano** [comment]
@Testato questo non è un problema perché al momento offro questo servizio solo su dispositivi Apple

**Comment by Testato** [comment]
Allora non ti serve nulla di quello che ho fatto, e credo che tu non possa proprio fare in nessun modo perché né ffmpeg né inputstream supporta il Drm apple

**Comment by ilariafabiano** [comment]
@Testato non posso fare in nessun'altra modo? su i dispositivi Apple come fa girare tutto questo?

**Comment by Testato** [comment]
Su Jobs la penso come Stallman 😅

**Comment by Testato** [comment]
La tua app é opensource ?
Posta il link ai sorgenti

**Comment by ilariafabiano** [comment]
@Testato non capisco cosa centra questo con la mia richiesta! Capisco che la pensi come Stallman ma se tutti i software fossero Open Source come si potrebbe vivere di questo? Se non vuoi aiutare semplicemente non rispondere.

**Comment by Testato** [comment]
Stai chiedendo aiuto gratis su un sito che sposa l'open source
Se non noti l'assurdità é un problema tuo

**Comment by ilariafabiano** [comment]
Ho chiesto qui perché il plugin per Kodi funziona, non ti ho chiesto mica di scrivermi il codice! Volevo solo delle informazioni tutto qui! Grazie per la disponibilità!
