### ISSUE TITLE
Il plugin crasha durante lo streaming live di La7

### ISSUE THREAD

**Issue by Mat-Ley** [luivit/plugin.video.rivedila7#30]
Salve, ho installato l'ultima versione del plugin su FireTv e Kodi 18.5 Leia. Come da titolo la diretta streaming di La7 va in crash ritornando al menu principale dell'amazon TV. Praticamente va in crash anche Kodi. Grazie,

**Comment by Testato** [comment]
Mi é capitato varie volte e sembra dipende da loro.
Se lanci firefox e guardi la diretta sul sito vedrai che capita lo stesso

**Comment by Mat-Ley** [comment]
OK, grazie mille!

**Comment by Testato** [comment]
Dammi conferma se provi, grazie

**Comment by Mat-Ley** [comment]
Si. Fino all'altro ieri usavo Firefox perché non riuscivo ad aggiornare la versione 3.1.1 dello script. In effetti ogni tanto perde la connessione e bisogna ricaricare la pagina.

**Comment by Testato** [comment]
Ok grazie della conferma.
Lascio aperta la issue nel caso altri vogliano segnalare altri test o possibili idee per mitigare il problema.
Già se riuscisse a non far chiudere Kodi sarebbe una buona cosa

**Comment by aiscrim** [comment]
A me dall’ultimo update di mesi fa il live streaming non parte proprio più. Dice “Unable to view this program”. Che può essere?
Sono su una Android Tv, Kodi aggiornato alla 18.5.

**Comment by Mat-Ley** [comment]
Anche a me aveva fatto così. Solo cercando su google, ho trovato questa pagina e l'esistenza della nuova versione. L'ho scaricata con downloader e installata manualmente.

**Comment by Testato** [comment]
Perché i tizi di Kodi non hanno ancora accettato la nuova versione.
O aspetti ancora qualche giorno, oppure installi manualmente il .zip

**Comment by NowhereGuys** [comment]
Ragazzi qualcuno potrebbe spiegarmi dove e come scaricare il file zip del 4.2.0? Anch'io fermo alla 3.1.1 :(( grazie

**Comment by Testato** [comment]
https://github.com/luivit/plugin.video.rivedila7/archive/master.zip

**Comment by NowhereGuys** [comment]
Ora va tutto alla grande! Grazie per il supporto e complimenti per il lavoro svolto!!

**Comment by aiscrim** [comment]
Anch'io con lo zip ho risolto, grazie mille!
