### ISSUE TITLE
Possibile login?!

### ISSUE THREAD

**Issue by Chazy12** [luivit/plugin.video.rivedila7#31]
È possibile aggiungere una sezione per il login?! Perché, senza login, si possono vedere le trasmissioni on demand solo di una settimana. Con il login, anche degli anni precedenti.
Grazie 🙏

**Comment by Testato** [comment]
???
Fai un esempio concreto

**Comment by Chazy12** [comment]
Sul sito (o l'applicazione) se effettui il login, puoi vedere puntate più vecchi di una settimana..

**Comment by Testato** [comment]
Sul nostro plugin non c'è bisogno perché i programmi sono sempre presenti in sezione On demand.
Cioè se vuoi vedere PropagandaLive di anno scorso vai in sezione Ondemand e te la guardi

**Comment by Chazy12** [comment]
Io ho provato con Atlantide, ma ci sono solo le ultime 7 puntate..

**Comment by Testato** [comment]
Si, ma perché non sono proprio memorizzate le più vecchie, é una scelta che fanno programma per programma.
Perché sul sito come fai a vedere Atlantide di anno scorso ?

**Comment by Testato** [comment]
Comunque mi interessa capire questa cosa, mi metti il link ad un programma dove con il login hai più puntate ? E dove si fa l'account ?

**Comment by Testato** [comment]
@Chazy12 
Puoi spiegare meglio sta cosa con un esempio ?

**Comment by Testato** [comment]
Issue chiusa per mancata risposta
