### ISSUE TITLE
Alcuni contenuti Rivedila7 non sono indicizzati

### ISSUE THREAD

**Issue by vanniaz** [luivit/plugin.video.rivedila7#32]
Ciao, il plugin funziona molto bene però ci sono alcuni contenuti che nel sito appaiono ma dal plugin non sono accessibili, ad esempio questo:
https://www.la7.it/non-classificati/rivedila7/professor-t-29-02-2020-310437
(la stessa cosa succede per altri video collocati nei NON CLASSIFICATI)

Si potrebbero indicizzare nel plugin anche i contenuti non classificati?

La colpa è del sito La7 che è gestito male e sbaglia a classificare alcuni video.
Ad esempio cercando PROFESSOR T appaiono le puntate della "Mala Educaxxxion", e i video di PROFESSOR T sono finiti nei "non classificati".
Però se il plugin potesse individuare anche i non classificati il problema sarebbe risolto.
Grazie!
Giovanni

**Comment by Testato** [comment]
Ottimo suggerimento,
vedo subito il da farsi

**Comment by Testato** [comment]
allora la situazione è questa:
La sezione non-classificati è gia' presente sul plugin (Ondemand-->Video non catalogati 1)
pero' la pagina sulla quale viene fatto lo scraping non presenta il video che tu indichi. 
La pagina sulla quale lavora il plugin è questa https://www.la7.it/non-classificati/rivedila7 e come vedi il video che cerchi non c'e'.
In alternativa il plugin puo' lavorare sulla pagina ancora precedente cioe' https://www.la7.it/non-classificati ma come vedi nemmeno qui è presente.
Quindi non c'e' soluzione, il plugin non fa (e non so se tecnicamente sarebbe possibile) una indicizzazione a livello di directory web

**Comment by vanniaz** [comment]
Grazie della risposta velocissima, in effetti temevo che non fosse possibile.

Ti vorrei chiedere un ultimo aiuto: conoscendo il link al video (che si trova abbastanza facilmente cercando m3u8 nel sorgente della pagina) esiste un modo per vederlo in Kodi?
Avevo provato a fare un file .strm con i link ai video che mi interessavano, ma Kodi non li riproduce, credo per un problema di DRM che invece il tuo plugin riesce a gestire (almeno credo che il motivo sia questo).

A voler esagerare sarebbe bello poter fare la ricerca sul sito La7 direttamente dal plugin, ma adesso non mi voglio allargare troppo con le richieste...

Grazie ancora
Giovanni

**Comment by Testato** [comment]
si ti confermo che Professor T è criptato, come ad esempio Dead Drop Diva, sara' questione di permessi.
Daltronde essendo una tv gratuita non avrebbe senso nemmeno applicarla la criptazione, se lo hanno fatto, anche alla diretta, sara' per obblighi contrattuali. 

Per l'idea di poter fare la ricerca dal plugin è una bella idea, non so quanto di facile attuazione ma di certo si puo' fare.
Fai una cosa, chiudi questa Issue e ne apri un'altra come Feature Request per la funzione Cerca

**Comment by vanniaz** [comment]
OK (scusa il ritardo) chiudo la issue e apro una feature request.
Effettivamente tramite la ricerca del sito (https://www.la7.it/ricerca?op=Cerca&query=...) appaiono anche i contenuti "orfani", che non sono elencati nelle categorie.
Non so però dire quanto sia facile o difficile gestire il risultato della ricerca, sei sicuramente più esperto tu!
