### ISSUE TITLE
Diretta con Glitch

### ISSUE THREAD

**Issue by jyan1992** [luivit/plugin.video.rivedila7#36]
Ciao ragazzi! 
Vista l'impossibilità di castare con webvideocast direttamente la diretta sul box android (Tim box) per i problemi dei drm (se avete una soluzione sono tutto orecchie 😂) ho provato l'ultima versione del plugin la 4.3.1 ma nella diretta pur vedendosi, è piena di glitch, non capisco se dipende dalla mancanza di qualche componente aggiuntivo o se c'è qualcos'altro che va fatto. Grazie mille, e soprattutto grazie allo sviluppatore!

**Comment by Testato** [comment]
https://github.com/luivit/plugin.video.rivedila7/issues/30

**Comment by jyan1992** [comment]
Ho scaricato proprio lo zip da quel post, ma i glitch rimangono

**Comment by Testato** [comment]
Allora non hai letto bene il post :-)
Non c'è soluzione, é la7 che si blocca ogni tanto, anche se lo guardi direttamente con Chrome sul Pc fa così

**Comment by jyan1992** [comment]
Guardando con browser Mozilla (versione Android TV) direttamente dal sito non glitcha, ma qualche volta capita che si impalli nel caricamento. Dal post sembrava con gli ultimi commenti che avesse risolto 😊

**Comment by jyan1992** [comment]
C'è un link diretto per riuscire a castare direttamente senza il solito errore dei drm? Scusami, so che va off topic rispetto al plugin 🤐

**Comment by Testato** [comment]
Di stream ufficiale uno c'è né, ed è quello che uso nel plugin ed é protetto con Drm.

**Comment by jyan1992** [comment]
È possibile estrapolare il link che hai usato nel plugin? 
https://stream.la7.it/out/v1/fe849af8150c4c51889b15dadc717774/index.m3u8
https:// d15umi5iaezxgx.cloudfront.net/OUT/HLS/Live .m3u8

Io trovo questi che non mi fa castare :/

**Comment by Testato** [comment]
Ad esempio sto guardando propaganda live e si é bloccato un paio di volte in 3 ore

**Comment by jyan1992** [comment]
Si esattamente, anche io stavo guardando propaganda, il problema, che forse non ho spiegato bene è che il video risulta glitchato e pixellato, con Firefox invece il problema è che ogni tot si incanta proprio il caricamento interrompendo la visione.

**Comment by Testato** [comment]
Non sono due problemi diversi, non riescono a trasmettere senza errori da quando sono passati al Drm, poi magari kodi reagisce in un modo il browser in un altro, ma sono loro che hanno errori di trasmissione
