### ISSUE TITLE
Plug in (and kodi) crash with la7 live start

### ISSUE THREAD

**Issue by robertucci** [luivit/plugin.video.rivedila7#37]
Kodi crashes when starting la7/la7d live. No problem for replay functions

**Comment by Testato** [comment]
Che versione stai usando ? Su che macchina ?

**Comment by robertucci** [comment]
Scusami. Ho verificato e stavo utilizzando una kodi ancora in beta. Ho aggiornato kodi e adesso funziona. Cmq android 9 su TV box + kodi 18.6 + plug in versione attuale
