### ISSUE TITLE
Live Streaming not working in Linux

### ISSUE THREAD

**Issue by mattange** [luivit/plugin.video.rivedila7#38]
Hi - first and foremost thank you for the excellent work. 
I note that the plugin works fine for on demand content but on live streaming of TV it appears to be crashing / just would not do anything...
I have Kodi 18.8 on Arch Linux and the plugin version is 4.
I have also Kodi 18.+ (Can't remember exactly) on Windows 10 and on that machine live streaming appeare to be working just fine).
Could it be an issues with some other libraries in Linux? Perhaps the underlying Google codec I understand being used in this project?

**Comment by Testato** [comment]
Ciao Matteo,
parliamo come mamma ci ha fatto :-)

Non ho mai rpovato il plugin su Arch (che mi sta anche estremamente antipatico :-) )
Farei comunque un paio di prove:
- la release attuale del plugin è 4.4.0, controlla, altrimenti aggiorna
- con le ultime due release di Kodi non si sa perche' ma non funziona piu' il plugin su Android, non vorrei che magari anche Arch rientra in questo problema. Per capire se questo è il caso installa Kodi 18.6 e riprova

**Comment by mattange** [comment]
Grazie, easier said than done on a rolling distribution that I still like for exactly that reason!
Vedrò come fare, doves Sia Verde news please update me.

Regards

**Comment by cunidev** [comment]
@mattange potresti postare il log di errore esatto di kodi in modo da poter diagnosticare il crash?

**Comment by Testato** [comment]
chiuso per mancanza di risposta da perte dell'utente

**Comment by mattange** [comment]
Sorry guys i missed this question some time ago and realised now you closed.

Sono sicuro il plugin sia attuale 4.4.0 ma ho avuto pochissimo tempo da ottobre e non ho avuto occasione di usare il plugin (che comunque risulta utilissimo quando ho occasione di guardare TV live!)
Se riesco a scaricare il log (come faccio btw?) posso sicuramente post here.
