### ISSUE TITLE
V.19 Matrix

### ISSUE THREAD

**Issue by MarcoViti** [luivit/plugin.video.rivedila7#39]
ciao, ci sono speranze di avere il tuo add-on su Kodi V.19 Matrix?

Grazie

**Comment by Testato** [comment]
sicuramente quando uscira' ufficialmente la V19 lo aggiorneremo

**Comment by MarcoViti** [comment]
> sicuramente quando uscira 'ufficialmente la V19 lo aggiorneremo

Versione ufficiale di Kodi 19 Matrix... confermo uscita

**Comment by Testato** [comment]
Ci sto lavorando orora :-)

**Comment by MarcoViti** [comment]
Grande ......
Grazie

**Comment by MarcoViti** [comment]
Plugbin appena installato Funziona benissimo ...... Versione 5.0.0 (2021-02-28)

Grazie
