### ISSUE TITLE
Plugin non funzionante e fuori dai repository ufficiali dopo aggiornamento a Kodi Matrix

### ISSUE THREAD

**Issue by Maxwell-hash** [luivit/plugin.video.rivedila7#43]

**Comment by Testato** [comment]
Confermo.
Vedo nel fine settimana se è facile sistemare.
Poi per il repo non so, si dovrà pubblicare verso matrix o tenerlo su entrambi, 18 e 19
@luivit

**Comment by Maxwell-hash** [comment]
Grazie per la veloce risposta e grazie per il lavoro che fai su questo plugin. Sono un italiano che vive all'estero e mi torna utilissimo

**Comment by Testato** [comment]
aggiornamento:
ho tutto funzionante al 90%, manca sezione Replay e thumb in sezione OnDemand.
Appena risolvo pubblico la ver. 5.0.0 :-)

**Comment by Maxwell-hash** [comment]
Grande. Grazie.

**Comment by Testato** [comment]
Fatto.
Scaricate da qui la nuova versione finchè non sarà dinuovo presente sul repo Kodi :-)

**Comment by filo1234** [comment]
Ciao, a me da questo errore..:
 CAddonInstallJob[plugin.video.rivedila7]: La dipendenza da xbmc.python versione 2.25.0 potrebbe non essere soddisfatta.

**Comment by Testato** [comment]
Hai installato dal repo kodi giusto ?
Non è ancora aggiornato sul repo, devi scaricare da qui il .zip e installarlo manualmente

**Comment by Testato** [comment]
> Grazie per la veloce risposta e grazie per il lavoro che fai su questo plugin. Sono un italiano che vive all'estero e mi torna utilissimo

Allora potrebbe interessanti questo altro mio Plugin ;-)
https://github.com/Testato/plugin.video.repubblicaitaliana

**Comment by filo1234** [comment]
> Hai installato dal repo kodi giusto ?
> Non è ancora aggiornato sul repo, devi scaricare da qui il .zip e installarlo manualmente

matrix è installato da launchpad:
kodi:
  Installato: 2:19.0+git20210219.1315-f44fdfbf67-0+final~focal
  Candidato:  2:19.0+git20210219.1315-f44fdfbf67-0+final~focal
  Tabella versione:
 *** 2:19.0+git20210219.1315-f44fdfbf67-0+final~focal 500
        500 http://ppa.launchpad.net/team-xbmc/ppa/ubuntu focal/main amd64 Packages
        500 http://ppa.launchpad.net/team-xbmc/ppa/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status
     2:18.9+git20201024.0821-final-0focal 500
        500 http://ppa.launchpad.net/team-xbmc/ppa/ubuntu focal/main amd64 Packages
        500 http://ppa.launchpad.net/team-xbmc/ppa/ubuntu focal/main i386 Packages
     2:18.6+dfsg1-2ubuntu1 500
        500 http://it.archive.ubuntu.com/ubuntu focal/universe amd64 Packages

il plugin l'ho scaricato da qui:
https://github.com/Testato/plugin.video.rivedila7

plugin.video.rivedila7-master.zip
quando lo installo mi da l'errore che ho descritto prima

**Comment by Testato** [comment]
Devi scaricarlo da qui, da questo repo :-)

**Comment by filo1234** [comment]
> Devi scaricarlo da qui, da questo repo :-)

azz che idiota :( continuavo ad installare l'altro da una dir vechia mmmmmmmmmmmmmmmmmmmmmmm grazie!
funzia!

**Comment by ZeeD** [comment]
Solo una domanda: la versione 5.0.0 è compatibile *anche* con kodi 18?
