### ISSUE TITLE
On demand non funzionante per Kodi 18.9 

### ISSUE THREAD

**Issue by Fabrizio-93** [luivit/plugin.video.rivedila7#47]
@Testato puoi rendere compatibile l'ultimo update 5.1.0 con la versione di kodi 18.9? l'ondeamand non funziona più con la vecchia versione 4.6.0, non uso kodi 19 perchè molti addon non sono compatibili Grazie
P. S. Ho cancellato il post dall'altra sezione

**Comment by Testato** [comment]
Avevo già fatto tutto :-)

https://github.com/luivit/plugin.video.rivedila7/issues/46
