### ISSUE TITLE
La 7 ondemand non funziona su kodi 18.9

### ISSUE THREAD

**Issue by Fabrizio-93** [luivit/plugin.video.rivedila7#48]
@Testato puoi rendere compatibile l'ultimo update 5.1.0 con la versione di kodi 18.9? l'ondeamand non funziona più con la vecchia versione 4.6.0, non uso kodi 19 perchè molti addon non sono compatibili. grazie

**Comment by Fabrizio-93** [comment]
@Testato l'ho fatto bene adesso l'issues?

**Comment by Testato** [comment]
Anche prima era fatta bene.
L'ho chiusa perché ho risolto.
Ti ho postato la versione che ti serve.
Te la riposto https://github.com/luivit/plugin.video.rivedila7/issues/46

**Comment by Testato** [comment]
la riparo perchè mi sono accorto di un altro rpobelma.
Mi confermi che continua a non funzionare anche sull'attuale 4.7.0 ?
(è presente sul repo ufficiale quindi puoi aggiornare direttamente da kodi)

**Comment by Testato** [comment]
C'e' stato un aggiornamento di beautifulsoup4 e questo fa bloccare il funzionamento di alcuni programmi ondemand, ad esempio LA7 Prime.
Per ora la soluzione è installare la vecchia versione https://mirrors.kodi.tv/addons/leia/script.module.beautifulsoup4/script.module.beautifulsoup4-4.6.2.zip
