### ISSUE TITLE
Kodi18: Errore su alcuni programmi OnDemand

### ISSUE THREAD

**Issue by Testato** [luivit/plugin.video.rivedila7#49]
C'e' stato un aggiornamento di beautifulsoup4 e questo fa bloccare il funzionamento di alcuni programmi ondemand, ad esempio LA7 Prime.
Per ora la soluzione è installare la vecchia versione di BS4 e disabilitare l'aggiornamento automatico della stessa
https://mirrors.kodi.tv/addons/leia/script.module.beautifulsoup4/script.module.beautifulsoup4-4.6.2.zip

**Comment by Fabrizio-93** [comment]
> C'e' stato un aggiornamento di beautifulsoup4 e questo fa bloccare il funzionamento di alcuni programmi ondemand, ad esempio LA7 Prime.
> Per ora la soluzione è installare la vecchia versione e disabilitare l'aggiornamento automatico della stessa
> https://mirrors.kodi.tv/addons/leia/script.module.beautifulsoup4/script.module.beautifulsoup4-4.6.2.zip

@Testato ho installato questo zip ma la versione è rimasta la 4.7.0 e il problema dell'ondemand è rimasto come mai?

**Comment by Testato** [comment]
Il plug-in resta a 4.7.0, lo zip è la vecchia versione di BS4, quindi dopo averlo installato non devi aggiornare BeautifulSoup

**Comment by Fabrizio-93** [comment]
> Il plug-in resta a 4.7.0, lo zip è la vecchia versione di BS4, quindi dopo averlo installato non devi aggiornare BeautifulSoup

Grazie adesso funziona 👍🏻

**Comment by Testato** [comment]
Risolto

https://github.com/xbmc/xbmc/issues/19455
