### ISSUE TITLE
Settimana + Archivio

### ISSUE THREAD

**Issue by Testato** [luivit/plugin.video.rivedila7#5]
Ottimo plugin :-)

Il sito di La7 non è purtroppo coerente, su alcuni programmi le vecchie puntate sono al link /settimana
Esempio PiazzaPulita:
http://www.la7.it/piazzapulita/rivedila7/settimana

Su altri programmi invece  le vecchie puntate sono su link /archivio
Esempio DiMartedì:
http://www.la7.it/dimartedi/rivedila7/archivio

Al momento quindi tutti i format con le puntate su /archivio non sono accessibili via plugin.

Vedo un paio di soluzioni, o si crea un ulteriore livello di scelta dopo ogni programma, tipo dopo aver scelto DiMartedi dalla lettera D si deve scegliere Week o Archive e poi ricevi l'elenco puntate, oppure si sommano sempre le puntate di settimana+archivio eliminando eventuali duplicati

**Comment by luivit** [comment]
ho appena provato sia piazzapulita che dimartedì, funzionano. Puntate vecchie di quanto?

**Comment by Testato** [comment]
Piazza pulita l'anno cambiato stamattina, a conferma dell'incoerenza ;-)

Ho trovsato un altro esempio Atlantide
http://www.la7.it/atlantide/rivedila7

Se vedi hai le due tab gialle, Settimana e Archivio
Le  puntate che sono in Archivio non vengono visualizzate dal plugin
http://www.la7.it/atlantide/rivedila7/archivio

**Comment by luivit** [comment]
ok, capito appena ho tempo aggiungo qualche controllo in pù

**Comment by luivit** [comment]
ho notato che i link in /archivio visualizza tutti i video, controlla con la nuova versione :)

**Comment by Testato** [comment]
E no :-)

Hai spostato l'accesso ai video da /settimana ad /archivio. Quindi si perdono i video in /settimana.
A volte quelli nel percorso /settimana vengono copiati anche in /archivio e quindi si puo' andare fuori strada con la diagnosi, ma l'unico modo per vederli tutti e' sommare i video in /settimana con quelli in /archivio.

Guarda Otto e Mezzo ad esempio.
Con la versione 0.0.9 vedevamo solo quelli in /settimana, con l'attuale tua versione 1.0.0 vediamo solo quelli in /archivio

Controlla direttamente via browser a questi link
http://www.la7.it/otto-e-mezzo/rivedila7/settimana
http://www.la7.it/otto-e-mezzo/rivedila7/archivio

**Comment by luivit** [comment]
ho appena inviato una nuova versione, ora visualizza sempre i video di "archivio", poi se ci sono video in "settimana" vengono inseriti in testa alla prima pagina. Possono esserci dei duplicati, un po' difficile filtrare purtroppo, spesso hanno anche nomi diversi...inizia a provare questo :)

**Comment by Testato** [comment]
Ottimo, testato su più programmi tutto ok.
Doppioni non ne ho visti, esempio su Atlantide sembra esserci un doppione di Scacco alla terra, ma in realtà hanno sbagliato loro, perché anche sul sito lanciando la puntata di dicembre poi parte quella di novembre:-)
Grazie

**Comment by Testato** [comment]
Questa tua modifica che eprmetteva di vedere i video elencati nella tab Settimana, mi sono accorto che non funzionava su tutti i rpogrammi.
Scava, scava ho capito il perche', su alcuni rpogrammi la tab Settimana e' visibile anche se aggiungi ?page=0 all'indirizzo, mentre su altri non e' presente, ma e' presente solo la tab Archivio :-)

Su questi rpogrammi per avere la tab Settimana presente si deve accedere all'indirizzo senza ?page=0

Che accozaglia di sito :-)

Ho risolto la cosa nella release mia versione 1.4.0 https://github.com/luivit/plugin.video.rivedila7/pull/14

p.s. sei daccordo ad aggiungermi nel progetto, cosi' manteniamo assieme il programma ?
