### ISSUE TITLE
Feature request: uso delle release di github

### ISSUE THREAD

**Issue by ZeeD** [luivit/plugin.video.rivedila7#50]
Ciao.
tra il passaggio di kodi e i recenti improvement diventa difficile recuperare la versione "giusta" del plugin.
Se poteste taggare le release, poi sarebbe più facile accedervi tramite un unico collettore come https://github.com/luivit/plugin.video.rivedila7/releases

**Comment by Testato** [comment]
Le versioni "giuste" sono nel repo ufficiale Kodi, sia per Kodi18 che Kodi19.
Qui non serve proprio venire se non per l'apertura di eventuali issue.

Attualmente chi usa ancora Kodi18 troverà nel repo la 4.7.0 mentre chi già usa Kodi19 troverà la 5.1.0
