### ISSUE TITLE
Kodi18 - Errore su play canali live con IA 2.4.5

### ISSUE THREAD

**Issue by ZeeD** [luivit/plugin.video.rivedila7#51]
Ciao.
Sono su Kodi 18 (non so se è collegato all'errore, ma ho appena aggiornato beautifulsoup4 alla versione 4.9.3 con le dipendenze fixate).

Non riesco a fare il play di dirette e "rivedi".
Nel caso delle dirette (sia la7 che la7d) ho un errore in ui, nei "Rivedi" sembra non trovi nulla

Nei log vedo
```
2021-03-26 14:29:11.452 T:1937152448   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
2021-03-26 14:29:14.978 T:1462588288   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.rivedila7/addon.py", line 3, in <module>
                                                from resources.lib import plugin
                                              File "/storage/.kodi/addons/plugin.video.rivedila7/resources/lib/plugin.py", line 881, in <module>
                                                play_dirette(url_live_la7,True)
                                              File "/storage/.kodi/addons/plugin.video.rivedila7/resources/lib/plugin.py", line 132, in play_dirette
                                                titolo_diretta=re.findall(regex5, html)[0]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
```

**Comment by ZeeD** [comment]
ho fatto un veloce check sui sorgenti, non l'ho testato, ma #52  dovrebbe fixare il problema

**Comment by lorenzos** [comment]
> non l'ho testato, ma #52 dovrebbe fixare il problema

L'ho testato io, e vi confermo che funziona.

Per @ZeeD, basta che vai nella cartella del plugin installato, modifichi il sorgente come hai fatto qui e lo ricompili al volo, per esempio:

```
$ cd ~/.kodi/addons/plugin.video.rivedila7/resources/lib
$ vim plugin.py # O qualsiasi cosa usi per modificare il codice
$ python -O -m compileall plugin.py
```

**Comment by Testato** [comment]
A che serve compilare ?
È un linguaggio interpretato no ?
Modifici il file salvi e funziona ;-)

Questa modifica se ho capito gestisce eventuali spazi nei titoli dei programmi in diretta.
Mica intendi anche altro ?

**Comment by lorenzos** [comment]
@Testato Ho pensato di compilare perché ho visto il file binario `plugin.pyo` accanto a `plugin.py`. Sinceramente non ti so dire se avrebbe funzionato anche senza ricompilare, non ho provato. Non ti so neanche dire se quel byte-code ottimizzato l'ha magari generato una particolare configurazione del mio Kodi (OSMC), oppure se è presente anche nel pacchetto sul repository...

Detto questo, sì, è lo scraping del titolo, ma evidentemente, a causa di una modifica di La7 sugli spazi accanto al segno `=`, il match della regex falliva e generava un errore non catturato. La modifica di @ZeeD dovrebbe rendere il match un po' più robusto ed indipendente da presenza, tipo e numero di quegli spazi vuoti :smile: 

La modifica sistema la Live, nel senso che da pochissimi giorni aveva smesso di funzionare anche con IA non aggiornato. Il problema con l'aggiornamento di IA è un discorso a parte, ed immagino proprio resti.

**Comment by Testato** [comment]
Il .pyo lo crea in automatico Kodi, quindi quando fai modifiche poi lui lo ricrea.
Puoi anche cancellarli, al boot lo ritrovi.

Perfetto quindi devo implementare questa modifica sia sulla versione Kodi 18 che 19.

Ma per il rivedi invece ? Io ho provato ora e non ho elenco vuoto, e questa regex non c'entra nulla con rivedi

**Comment by lorenzos** [comment]
Ah ecco, beh, meglio, edito la mia risposta. Scusa ma di Python ne so praticamente zero :smile: 

Per il Rivedi non so, non ho testato, e sinceramente non avevo neanche notato fosse menzionato nel primo commento. Mi ero fissato sulla Live perché sapevo non funzionasse più.

**Comment by ZeeD** [comment]
@Testato scusa, ma non credo che IA c'entri qualcosa con questa segnalazione: il problema è che l'html dove è definito il titolo è cambiato (ho fatto un check con waybackmachine) e quindi il plugin andava in errore.

**Comment by Testato** [comment]
Si, chiaro.
Ho modificato il titolo specificando la release di IA per far capire che era un bug aggiuntivo al discorso IA che è ancora aperto.
Fortunatamente hanno iniziato a lavorare alla mia segnalazione. Oggi devo fare dei test.
Quando sarà funzionante la live su Kodi19 lasciamo definitivamente il supporto a Kodi18

**Comment by Testato** [comment]
@ZeeD 
Puoi invece spiegare meglio il problema che riferisci sulla sezione Rivedi ?
Non può centrarci il tuo fix perché quella variabile viene usata solo sulle due Dirette

**Comment by ZeeD** [comment]
@Testato 
hai ragione, sono due problemi scorrelati.

Non ho fatto debug, ma quello che vedo è che quando provo ad accedere alla sezione rivedi a volte ho un errore (e nei log vedo uno stacktrace riguardante il timeout della request verso https://www.la7.it/rivedila7/0/la7) a volte... semplicemente niente.
nei log non compare nulla e lato UI "rimango" nel menu iniziale.

Non mi sembra legato a bug veri e propri (ho provato anche a simulare la chiamata con lo stesso user agent ma dal mio pc riesco correttamente a recuperare la pagina) e forse è un problema del mio setup (soprattutto se il problema lo riproduco solo io)

**Comment by Testato** [comment]
ok allora chiudo questa issue e grazie per la regex
nel caso riesci a repllicare in modo meno saltuario il problema riapri una issue per Rivedi.

**Comment by Testato** [comment]
@ZeeD 
avevi ragione, Rivedi non funzionava, l'ho sistemato
Ho rilasciato la nuova versione per Kodi18
https://github.com/luivit/plugin.video.rivedila7/archive/refs/heads/feature/kodi-18.zip

Ho convinto i tizi di IA di backportare gli aggiornamenti anche verso kodi18, hanno rilasciato la versione 2.4.8 e quindi ora funziona tutto correttamente sia su Kodi18 che Kodi19 (sul 19 hanno rilasciato la 2.6.13)

**Comment by Testato** [comment]
questa è una versione compilata per Linux per chi è ancora su Kodi18
Sottolineo che non supportiamo piu' pero' kodi18 quindi le nuove versioni sono solo per Kodi19
https://f.mjh.nz/ia/6742307-linux-x86_64.zip
[6742307-linux-x86_64.zip](https://github.com/luivit/plugin.video.rivedila7/files/6583758/6742307-linux-x86_64.zip)
