### ISSUE TITLE
ERRORE DI ADDON

### ISSUE THREAD

**Issue by step1975roma** [luivit/plugin.video.rivedila7#54]
SALVE ,  A TUTTI CE UN PO DI CONFUSIONE ULTIMAMENTE MA VORREI CAPIRE SE LA VERSIONE PER KODI 18.9 VIENE ANCORA AGGIORNATA VISTO CE KODI 19 DOVE ALCUNI ADDON ANCORA NON FUNZIONANO... LA SETTE NON FUNZIONA PIU' NE LO STREAMING DEI CANALI LIVE, E POSSIBILE SISTEMARE TUTTO IO USO A ORA LA VERSIONE 4.7.0, E NON SO MA DA CIO CHE SI DICE LE ULTIME VERSIONI SU KODI 18 NON SI POSSONO INSTALLARE. QUINDI SE FOSSE COSI' BISOGNA MANTENERE E AGGIORNARE LE VERSIONI DI CHI USA KODI 18 SPERO SI PUO RISOLVERE TUTTO TANTA GENTE NON PASSA A KODI 19 ANCORA SE GLI ADDON NON SONO COMPATIBILI... VORREI RIPOTER VEDERE I CANALI LIVE DI LA 7.. BUONA GIORNATA A TUTTI E BUON LAVORO E GRAZIE PER QUELLO CHE FATE SPERO COMPRENDIATE CHE LE VERSIONI X KODI 18 ANCORA SONO UTILI.

**Comment by Testato** [comment]
non scrivere in maiuscolo please.

al momento sia su kodi19 che su kodi18 funziona tutto.

Su Kodi19 funziona in modo ufficiale, perche' oggi sono state accettate le modifiche ad Inputstream.adaptive 
Su Kodi18 l'aggiornamento di inputstream.adaptive non si sa se lo faranno o meno, dipende da loro, ma installando una vecchia versione di Inpustream.adaptive, al massimo la 2.4.5, funziona anche su kodi18

Oltre quindi alle versioni corrette di Inputstream, servono poi le ultime versioni del nostro plugin che sono queste:
LA7 per Kodi19
https://github.com/luivit/plugin.video.rivedila7/archive/refs/heads/master.zip

LA7 per Kodi18
https://github.com/luivit/plugin.video.rivedila7/archive/refs/heads/feature/kodi-18.zip

**Comment by step1975roma** [comment]
ciao innanzitutto grazie per la risposta, per quanto riguarda addon la sette tutto bene installato ma per  per l'altro  imput stream adaptive no mi dice sempre struttura non valida zip di una versione precedente 2.4.5 a me sembra strano tutto cio', perche se la 7d lo stream parte mentre e solo con la 7 che lo stream da questa schermata nera... e non parte, e le puntate di quella serie svegliati amore mio non partono, quando erano con .mpd le puntate andavano bene. non so cosa fare. se ai consigli bene accetti.

**Comment by Testato** [comment]
Hai risolto poi ?
Mi è arrivata notifica in email ma qui non vedo nulla

**Comment by step1975roma** [comment]
SI PER ORA RISOLTO E ARRIVATO UN AGGIORNAMENTO DI IMPUT STREAM... E ORA LA SETTE E ALTRO FUNZIONANO BENE, MA NON E CHIARO SE TUTTI ORA SI OCCUPERANNO DI AGGIORNARE GLI ADDON, PER LA VERSIONE 18 SPERO DI SI PERCHE SONO ARRIVATI DUE AGGIORNAMENTI E NON LI FA INSTALLARE PERCHE SONO SICURO PER LA VERSIONE 18 BO CE CONFUSIONE... GRAZIE PER IL TUO AIUTO.

**Comment by Testato** [comment]
Passa a kodi19 ormai kodi18 è abbandonato
