### ISSUE TITLE
Diretta la7 si blocca dopo pochi secondi

### ISSUE THREAD

**Issue by aiscrim** [luivit/plugin.video.rivedila7#55]
Ho installato sulla mia android tv l’ultima versione del plugin (5.2.0) su kodi 19, assicurandomi che ci sia anche l’ultima versione di InputStream Adaptive (2.6.13).
La diretta la7 parte bene, ma dopo circa 15 secondi si blocca e ritorna al menu del plugin. Stessa identica cosa per la7d.
Any ideas?

**Comment by Testato** [comment]
Me ne sono accorto oggi.
Avranno cambiato dinuovo.
Riporto dinuovo tutto a quelli di IA, purtroppo su questi problemi lato plugin non si può fare nulla

**Comment by Testato** [comment]
prova questa versione, fai dei test su lunghe durate
https://github.com/luivit/plugin.video.rivedila7/archive/refs/heads/master.zip

**Comment by bepsx** [comment]
Buonasera, io ho lo stesso problema su Kodi 18.7 installato su Raspberry OS. Ho anche provato la nuova versione messa a disposizione (peraltro Kodi mi avverte della dipendenza da Python 3 che potrebbe non essere soddisfatta...), ma il problema persiste.

**Comment by Testato** [comment]
per kodi18 c'e' l'apposita versione.
la trovi nel repo ufficiale kodi, scaricala da li'
pero' questo problema del blocco non lo toglie, questa versione di test non l'ho fatta per kodi18
passare a kodi19 ormai è obbligatorio

**Comment by rafhtl** [comment]
> prova questa versione, fai dei test su lunghe durate
> https://github.com/luivit/plugin.video.rivedila7/archive/refs/heads/master.zip

Questo funziona su kodi 19 e non si blocca piu' dopo 15s.
Sto usando inputstream versione inputstream.adaptive.so.2.6.8

**Comment by Testato** [comment]
Aggiorna all'ultimo inputstream 2.6.13

**Comment by Testato** [comment]
Ho aggiornato anche la versione per Kodi18, fatemi sapere se funziona
https://github.com/luivit/plugin.video.rivedila7/archive/refs/heads/feature/kodi-18.zip

**Comment by rafhtl** [comment]
funziona anche con inputstream 2.6.13
grazie

**Comment by lorenzos** [comment]
Confermo anch'io, OSMC con Kodi 18 e IA ancora downgradato alla 2.4.5.  
Prima dopo una decina di secondi si piantava lo stream, ora va liscio per ore.

**Comment by Testato** [comment]
Puoi aggiornare IA anche su kodi18 non serve più la versione vecchia

**Comment by ruabo** [comment]
> prova questa versione, fai dei test su lunghe durate
> https://github.com/luivit/plugin.video.rivedila7/archive/refs/heads/master.zip

Provato su Kodi 19, sento audio, no video (mac os 11.2.3 su m1) e poi si ferma dopo qualche secondo. Ho fatto prova anche con raiplay, vedo diretta ma non contenuti con drm. Che cosa devo verificare ? Widevine ? Non lo trovo nei plugin. Grazie!

**Comment by Testato** [comment]
Non diamo supporto a chi compra mele morse 😛

**Comment by aiscrim** [comment]
> prova questa versione, fai dei test su lunghe durate
> https://github.com/luivit/plugin.video.rivedila7/archive/refs/heads/master.zip

Ho appena fatto la prova, purtroppo stesso identico comportamento: parte bene ma dopo pochi secondi si blocca...

**Comment by ruabo** [comment]
> Non diamo supporto a chi compra mele morse 😛

Lungi da me ! Ho avuto il sospetto non dipendesse dal plugin e ho verificato con un'altra app che si appoggia a widevine. Un dettaglio. La versione 5.1 non chiedeva l'installazione di IAS, la 5.2 si e poi ha installato anche widevine. Qualche relazione al fatto che si senta solo l'audio ?

**Comment by Testato** [comment]
Va installata l'attuale versione scaricata da questo repo, quella del repo kodi non è aggiornata

**Comment by ruabo** [comment]
Sì, ho fatto così. Per scrupolo ho disinstallato e installato dallo zio sopra. Dà sempre 5.2 come versione, sento solo audio e niente video

**Comment by Testato** [comment]
Ho caricato le nuove versioni:

Kodi19 - Ver 5.3.0
https://github.com/luivit/plugin.video.rivedila7/archive/refs/heads/master.zip

Kodi18 - Ver 4.8.2
https://github.com/luivit/plugin.video.rivedila7/archive/refs/heads/feature/kodi-18.zip

**Comment by ruabo** [comment]
grazie. Rimossa e installata questa sopra. Il plugin riporta la 5.3 ora. Riproduce qualche secondo di solo audio, il timing parte da qualche secondo prima di 4:00 e poi arrivato a 4:00 si ferma

**Comment by Testato** [comment]
Se hai schermo nero è un problema di inputstream adaptive. Vai in My Plugin e fai uno screenshot della categoria Videoplayer, voglio vedere cosa c'è

**Comment by ruabo** [comment]
Questa ?
<img width="1184" alt="Schermata 2021-04-14 alle 23 32 53" src="https://user-images.githubusercontent.com/65824081/114782070-cebc9080-9d79-11eb-9e97-c9cb22679704.png">

**Comment by Testato** [comment]
Si è quella giusta.
Vai su La7 prime, Film, DropdeadDiva ti funziona ?
E poi guarda se ti funziona qualcosa da sezione Rivedi

**Comment by ruabo** [comment]
> Si è quella giusta.
> Vai su La7 prime, Film, DropdeadDiva ti funziona ?
> E poi guarda se ti funziona qualcosa da sezione Rivedi

Sì, in queste sezioni funziona tutto

**Comment by Testato** [comment]
Se hai visto Dropdeaddiva allora widevine funziona.
Hai provato ad aspettare ? Al momento capita che vedi i primi 30secondi della diretta, poi si blocca, poi riparte

**Comment by ruabo** [comment]
Niente da fare, diventa tutto rallentato, audio balbettante a tratti (ho 80 (ottanta) Mbit in download) e cursore lascia scie
<img width="1357" alt="screen" src="https://user-images.githubusercontent.com/65824081/114933473-ff173400-9e38-11eb-94c0-3dd99a951fac.png">

**Comment by Testato** [comment]
Bella storia.
Non ho nessun mac per provare, potrebbe essere una incompatibilità tra inputstream e le mele morse. Prova ad aprire una issue sul github di InputstreamAdaptive

**Comment by bepsx** [comment]
Ciao, ma la versione sulla repository ufficiale di Kodi 19 è già quella con la patch? Grazie.

**Comment by Testato** [comment]
Non ancora.
Scaricarla da qui https://github.com/luivit/plugin.video.rivedila7/archive/refs/heads/master.zip

**Comment by ca-83** [comment]
Ciao a tutti,
Stesso problema di ruabo su Android tv. Versione plugin la7 5.4. e IA 2.6.14. Ho provato a installare da file zip ma mi dà errore (installazione fallita). Non si sente audio e dopo poco rallenta. Prime non funziona. Grazie

**Comment by Testato** [comment]
Disinstalla prima il plugin, e poi reinstalli da file zip

**Comment by ca-83** [comment]
> Disinstalla prima il plugin, e poi reinstalli da file zip

Fatto più volte. Errore dovuto ad una “struttura non valida”

**Comment by Testato** [comment]
Metti il link allo zip che scarichi

**Comment by ca-83** [comment]
> Metti il link allo zip che scarichi

Mi scuso in anticipo per la mia ignoranza in materia e vi ringrazio per il sopporto, spero di aver compreso il suggerimento:ho scaricato il file zip dal link postato due giorni fa e ho provato a installarlo da usb su Android tv/Kodi ma l’installazione fallisce. Ora ho disinstallato Kodi e provato a installare nuovamente il plugin da zip su usb, stesso errore.

**Comment by Testato** [comment]
Hai installato Kodi19 ?
Usi questo zip per LA7 ?
https://github.com/luivit/plugin.video.rivedila7/archive/refs/heads/master.zip

Prova anche ad installare tutto sul tuo cellulare, vediamo se su telefono ti funziona

**Comment by ca-83** [comment]
Su Android tv box versione 19.sul cell posso scaricare solo la versione 18.9.
Si ho utilizzato quel link per scaricare zip messo su usb.ho anche provato ad impostare questa pagina come sorgente e scaricare il file zip da qui ma non ha funzionato molto bene

**Comment by Testato** [comment]
Invece di scaricare lo zip installa il plugin direttamente dal repo ufficiale di Kodi, internamente a kodi.

Fai stessa cosa anche sul telefono

**Comment by ca-83** [comment]
Su Android tv finalmente funziona!grazie

**Comment by ruabo** [comment]
Aggiornamento sul video che non partiva: ho risolto disabilitando l'accelerazione hardware nell impostazioni video (probabilemente c'è qualche problema con Rosetta 2). Ora il video parte, però sempre da 3:25, arriva a 4:00, si ferma qualche secondo, quindi ricomincia a vedersi il video sempre da 3:25 e si ripete il ciclo. Altri suggerimenti ? Grazie

**Comment by Testato** [comment]
Ma il video procede ?
Il fatto che a 4min si ferma è un bug di inputstream, però non lo fa sempre.
Che arriva a 4min e poi la barra torna indietro è normale, la7 ha 32sec di buffer

**Comment by ruabo** [comment]
il video procede fino a quando non arriva a 4:00, quindi si ferma per qualche secondo, popi riprende.
Oggi però funziona. Boh. Grazie. Il bug di inputstream è in corso di risoluzione ?

**Comment by Testato** [comment]
Stanno pensando su come implementare bene questa cosa del buffer da 32secondi. Fortunatamente all'inizio si blocca solo 2 o 3 volte poi è tranquillamente fruibile

**Comment by Testato** [comment]
Scaricate la versione 6.0
Oltre ad un profondo rework ho aggiunto un fix temporaneo per non fare piu' arrivare la barra alla fine dei 4.00 minuti
https://github.com/luivit/plugin.video.rivedila7/archive/refs/heads/master.zip

**Comment by mmacchia** [comment]
Ciao! Innanzitutto grazie per questo addon!
Vorrei segnalare che durante la giornata di ieri ho notato che la7 live non funziona: dopo qualche secondo il video si blocca e lo stream si interrompe. 
Questo su Kodi 19 con libreelec e inputstream adaptive versione 2.11.
Ho provato ad installare la versione 6.0.1 di questo addon sia dalla repository di Kodi che dalla branch master di gitthub. 
Inoltre con la versione 2.13 e 2.14 di inputsteam adaptive, lo stre live di LA7 non parte neppure. Qualcuno ha problemi simili?
Come posso tentare per risolvere?

**Comment by Testato** [comment]
Hai versioni vecchisdime di inputstream.
Ti serve inputstream.adaptive-2.6.15

Sia l'ultima versione 6.0.1 del plugin che la 2.6.15 di inputstream li trovi sul repo ufficiale.

LibteElec non so che politica usa per il repo, su alcuni Linux non trovi inputstream nel repo e devi installare tu manualmente la 2.6.15

**Comment by mmacchia** [comment]
Grazie per l'info, esiste una lista di requirements per ogni versione di questo addon?
Credo che la versione 2.6.15 non sia ancora disponibile nelle repository di libreelec.
Non mi è chiaro come installare inputstream adaptive dalla repository GitHub, su libreelec (a sua volta su arm), mi sembra che vada compilato su arm e poi spostato manualmente nella cartella addon. Ci provo tra poco, grazie!

**Comment by Testato** [comment]
Si va compilato perché è un plugin binario, su github c'è solo il sorgente.
Il nostro pligin ha solo inputstream come prerequisito che può creare problemi, ma in realtà solo su linux questo può diventare un problema, perché su android e su Windows viene installato in automatico il tutto
