### ISSUE TITLE
Debian - Errore download widevine

### ISSUE THREAD

**Issue by Rick654** [luivit/plugin.video.rivedila7#56]
Buonasera agli sviluppatori.
Sto usando il vostro addon la 7 su un kodi 19 installato su debian 10 buster.
Tuttavia, quando provo ad avviare la diretta la 7, mi viene chiesto di installare la widevine,
clicco su si, ma non scarica nulla, e mi appare un messaggio in inglese indicante l'assenza di segnale internet,
cosa assolutamente non vera.
Cosa posso fare per risolvere?

**Comment by Testato** [comment]
Leggi il Readme :-)

**Comment by Rick654** [comment]
Grazie per aver risposto, testato.
I contenuti rivedi e ondemand funzionano.

**Comment by Testato** [comment]
ho appena fatto una prova su Debian installato su PC e funziona.
Tu su che architettura stai installando ?

Hai prima installato IA con:
sudo apt install kodi-inputstream-adaptive

**Comment by Rick654** [comment]
Ciao Testato.
E' un sistema a 32 bit.
Inpustream adaptive, l'ho installato da synaptic.

**Comment by Testato** [comment]
È una Sbc ?
Che modello ?

**Comment by Rick654** [comment]
Perdonami, ti riferisci al PC?

**Comment by Testato** [comment]
No credevo usassi una sbc.
Quindi è un normale pc ? Che modello ? Processore ?

**Comment by Rick654** [comment]
Ok, Toshiba  Satellite A100 , intel core2 DUO.

**Comment by Testato** [comment]
Allora c'è nulla che posso fare, è sicuramente un problema lato tuo.
Chiudo per orala issue

**Comment by Rick654** [comment]
Loro chi?
Ho chiesto nel forum del SO e non ho ricevuto risposte.

**Comment by Testato** [comment]
Questo è il tool che gestisce il download di widevine.
https://github.com/emilsvennesson/script.module.inputstreamhelper

**Comment by Rick654** [comment]
Ah ok, grazie per la disponibilità.
