### ISSUE TITLE
"Resume from / Play from beginning" all'avvio della diretta

### ISSUE THREAD

**Issue by lorenzos** [luivit/plugin.video.rivedila7#59]
Per quale motivo all'avvio della diretta Kodi mi chiede (quasi) sempre in un modale se riprendere la riproduzione da un certo tempo, oppure se avviare dall'inizio? Non ha senso nel caso della live (mentre, per esempio, su Rivedi è comodo)... È un problema mio oppure è normale? Credo sia mesi che fa così, mi chiedevo quale fosse la causa e se è possibile disabilitare la scelta per evitare due tasti in più ogni volta :smile:

**Comment by Testato** [comment]
Sicuro tu abbia l'ultima versione ?
Ho tolto tempo fa questa funzione dai due canali Live

**Comment by lorenzos** [comment]
Sì, ultima versione, ma ho capito ora qual era il problema: avevo aggiunto tempo fa la diretta dal plugin nei preferiti di Kodi, prima della risoluzione, e la avviavo sempre da lì. Ho provato ad avviarla invece dal plugin, ed infatti non chiede nulla. Mi è bastato perciò rimuovere e aggiungere di nuovo il preferito per aggiornare la URL. Grazie mille per la veloce riposta.

**Comment by Testato** [comment]
Che strano, secondo me ci sarebbero gli estremi per l'apertura di una issue a Kodi.
Probabilmente:
1- quando si usa "Aggiungi ai preferiti" Kodi invece di creare uno shortcut crea una seconda copia del file. Cosa che può anche essere legittima ma...
2- quando viene aggiornato il plugin il file precedentemente copiato nei preferiti non viene aggiornato.

**Comment by lorenzos** [comment]
Sì, ho guardato un po' i sorgenti del plugin, e secondo me è così. La7 "genera" il menù e crea le sue URL. Quando io scelgo una voce del menù e la aggiungo ai preferiti, Kodi usa la URL che il plugin gli ha dato e la copia nel preferiti. A quel punto lì rimane così com'era. Se il plugin viene aggiornato e modifica il suo menù, cioè le URL dei suoi entry point, non vedo come Kodi possa aggiornare la URL nei preferiti a colpo sicuro, voglio dire, non c'è un modo univoco per mettere in relazione una URL precedente, non più presente nel plugin, ad una nuova. Non mi pare ci sia un ID che rimane invariato o che abbia senso usare semplicemente il posizionale, ho come l'impressione che l'identificativo sia la URL stessa...

**Comment by Testato** [comment]
Capisco.
Ma se disinstalli un plugin la disinstallazione tira via anche i suoi preferiti. Quindi una soluzione potrebbe essere che anche durante un update vegano tirati via i preferiti. Si ok poi devi ricrearlo a mano, ma sempre meglio del bug che va a creare ora

**Comment by lorenzos** [comment]
Capito, sì. Ne approfitto per chiederti un'altra cosa. Da quando ho "ricreato" il preferito, al click appare l'icona di caricamento, poi scompare quando viene visualizzato il nome del programma in corso, e da questo momento in poi rimane senza icona di caricamento fino all'avvio del video qualche secondo dopo. Prima invece, con l'URL vecchia, veniva visualizzata l'icona di caricamento dall'inizio fino alla fine. Così è un po' strano perché sembra che si sia bloccato con il nome del programma in alto, ti dà l'idea di aver finito di lavorare anche se non è così.

**Comment by Testato** [comment]
No a me non lo fa, fa un effetto di "Cliccato" quando appare il titolo ma subito ritorna normale.
Prova a cancellare la cache dei thumbnails, è un file, poi al boot ricrea tutto in automatico
