### ISSUE TITLE
Dir On-Demand

### ISSUE THREAD

**Issue by Testato** [luivit/plugin.video.rivedila7#6]
La cartellina che permette l'accesso a tutti i programmi non ha nessun nome, si potrebbe usare On-Demand ?
- Live Streaming
- La7 Replay
- On-Demand

**Comment by luivit** [comment]
L'item del menù ha già il testo impostato, se hai kodi in italiano vedrai "Tutti i programmi" altrimenti in inglese.

**Comment by Testato** [comment]
A me non appare, ho provato anche su Android (ver 0.0.9)
Ti allego screenshot, la terza directory non ha nome

![screenshot_2017-11-22-08-26-09](https://user-images.githubusercontent.com/6893841/33114922-4d17821a-cf5f-11e7-9c39-f11c1d69029b.png)

**Comment by luivit** [comment]
strano, prova ad impostare kodi in italiano, Anche qui appena ho tempo faccio delle prove

**Comment by Testato** [comment]
![screenshot_2017-11-22-18-30-55](https://user-images.githubusercontent.com/6893841/33141507-abc05216-cfb3-11e7-906e-6f1f971944c2.png)

**Comment by luivit** [comment]
ho uppato una nuova versione, https://github.com/luivit/plugin.video.rivedila7/archive/master.zip
Dovrebbe correggere il problema

**Comment by Testato** [comment]
Yep, thanks
