### ISSUE TITLE
Errore LA7 Live

### ISSUE THREAD

**Issue by marcocalm** [luivit/plugin.video.rivedila7#60]
Saltuariamente La7 Live non funziona, in kodi.log trovo questo errore:

plugin.py", line 80, in play_dirette
                                                       html = page.decode()
                                                   UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 471496: invalid continuation byte
                                                   -->End of Python script error report<--

Ho notato che specificando l'encoding latin-1 risolve il problema (non so pero' se ne possa introdurre un altro)
Ho modificato cosi' la linea in questione
html = page.decode(encoding='latin-1')

**Comment by Testato** [comment]
Grazie della issue.

Visto che latin può causare problemi con altri caratteri proviamo così

html = page.decode(errors='replace')

Questo sostituisce il carattere problematico con il default
Fammi sapere se risolve così aggiorno il plugin

**Comment by marcocalm** [comment]
Si, funziona anche cosi'.

Grazie!

**Comment by marcocalm** [comment]
Eh, poco prima, circa una mezz'ora il problema c'era, non ho ri-verificato
immediatamente. Ora ho provato e non c'e' piu'.
Appena ricapita verifico.

**Comment by marcocalm** [comment]
Confermo che funziona. In questo momento il problema e' presente, ho provato da due diversi sistemi contemporaneamente, uno con la fix e l'altro senza.

**Comment by Testato** [comment]
Grande 👍
Vuoi fare tu la PullRequest ?

**Comment by marcocalm** [comment]
Fatta, grazie, spero sia tutto ok
https://github.com/luivit/plugin.video.rivedila7/pull/61

Saluti
Marco

**Comment by Testato** [comment]
👍👍
