### ISSUE TITLE
Replay doesn't works

### ISSUE THREAD

**Issue by campipaolo** [luivit/plugin.video.rivedila7#62]
Hello everyone!

I'm running addon with kodi 19.4 (token from web site) on linux mint 19.2/libreelec 10.02/xiaomi stixk android 9/mtorola g22 android 12
The section "rivedi LA7/la7D" ("replay date) get an error 
Maybe website structure has changed or It seems must be entered a password?

Here my log file

https://paste.kodi.tv/ohegufucef

Thanks and sorry for my English

**Comment by MarcoAlici** [comment]
Hi, same here on ubuntu. My log file:
https://paste.kodi.tv/hazebikoni.kodi

**Comment by nonebutcarlo** [comment]
Same on Osx and FireTv and Leia. Cannot produce a log.

**Comment by Testato** [comment]
Raga siamo tutti italiani qui :-)

Dopo gli do uno sguardo

**Comment by scatarsi** [comment]
Hi there, I am using la7 inside kodi. In the last 3 days it’s impossible to access rivedila7. Only the streaming la7 live works

**Comment by Testato** [comment]
Non solo Replay ma anche alcuni programmi OnDemand tipo Una giornata particolare

**Comment by campipaolo** [comment]
> Non solo Replay ma anche tutte le altre sezioni non funzionano, ondemad, news, teche Grazie della segnalazione, appena ho un attimo approfondisco Grazie dei logs

Le dirette vanno, provato ora su 2 dispositivi diversi con differenti connessioni
Il resto è ovvio che non va, sono replay

**Comment by Testato** [comment]
Non é ovvio, perché le strutture fa parsare sono diverse, se tipo cambiano solo la sezione Replay puoi guardare le puntate da Programmi ma non da Replay.
Questa volta invece sembra un problema più generale

**Comment by campipaolo** [comment]
Inteso che è un contenuto non in diretta, e le dirette vanno
Quello che dici è un contenuto che non è in diretta, al di là della struttura e da dove viene posizionata nelle varie voci di menù delladdon

**Comment by Testato** [comment]
Non la vedo buona sta cosa, specialmente quel user:passwrd che vedo in uno dei log 😅

**Comment by campipaolo** [comment]
Già... È la prima cosa che ho notato dal mio log quando ho aperto il ticket issue
Vediamo come si evolve la situazione

**Comment by marcogaio** [comment]
Idem qui, kodi su OSMC/Vero 4K+:
```
2022-10-23 21:21:01.785 T:2819     INFO <general>: VideoPlayer::OpenFile: plugin://plugin.video.rivedila7/?mode=rivedi_la7&play=https%3A%2F%2Fwww.la7.it%2Fpropagandalive%2Frivedila7%2Fpropaganda-live-puntat
a-del-21102022-22-10-2022-456836&titolo=Propaganda+Live&thumb=https%3A%2F%2Fkdam.iltrovatore.it%2Fp%2F103%2Fsp%2F10300%2Fthumbnail%2Fentry_id%2F0_4pcnv9t0%2Fwidth%2F600%2Fquality%2F100%2Fname%2F0_4pcnv9t0.j
pgname%2F0_4pcnv9t0.jpg_vrs8867name%2F0_4pcnv9t0.jpg&plot=Diego+Bianchi+e+Marco+Dambrosio+con+Kasia...
2022-10-23 21:21:02.242 T:2819    ERROR <general>: CCurlFile::Stat - Failed: HTTP response code said error(22) for https://awsvodpkg.iltrovatore.it/local/hls/,/content/servizio-di-notifiche-push" title="LA7
 Notifiche Push"></a></div></div></div></div><div class="main-toolbar "><div class="logo" itemscope itemtype="http://schema.org/Organization"> <a itemprop="url" href="/" title="la7" rel="home" id="logo"> <i
mg itemprop="logo" src="/sites/default/themes/la7/newcss/assets/img/la7_logo.svg" alt="La7"/> </a></div><div class="toggler js-open-menu-mobile"><div class="line"></div><div class="line"></div><div class="l
ine"></div><div class="dot"></div><div class="dot"></div><div class="dot"></div><div class="dot"></div><div class="dot"></div><div class="dot"></div><div class="dot"></div><div class="dot"></div><div class=
"dot"></div></div><div class="main-menu "><ul class="menu clearfix"><li class="first leaf"><a href="/programmi" title="">Programmi</a></li><li class="leaf"><a href="/guida_tv" title="">Guida Tv</a></li><li 
class="leaf"><a href="/rivedila7" title="">Rivedila7</a></li><li class="leaf"><a href="/dirette-tv" title="">Live</a></li><li class="leaf"><a href="/i-protagonisti" title="">Teche La7</a></li><li class="lea
f"><a href="/la7retweet" title="">La7retweet</a></li><li class="last leaf"><a href="/podcast" title="">Podcast</a></li></ul></div><div class="live"> <a href="/dirette-tv"> live </a></div><div class="contain
er-logo-alt-mobile"><div class="logo-alt-mobile logo-la7d-alt-mobile"> <a href="/la7d" title="la7D" rel="home"> <img src="/sites/default/themes/la7/newcss/assets/img/la7d_logo_color.svg" alt="La7D"/> </a></
div></div><div class="ricerca js-overlay-ricerca-open"></div><div class="header-property-mobile-container"><div class="container-heading"><h1 class="mobile-title">Propaganda Live</h1><div class="dots js-dot
s-prop"><div class="dots-inner"><div class="dot-el"></div><div class="dot-el"></div><div class="dot-el"></div></div></div></div><div id="block-views-property-new-block-1" class="list-container js-header-pro
p-list"><ul><li class="list-item list-item-i"> <a href="/propagandalive/rivedila7"> Puntate </a></li><li class="list-item list-item-i"> <a href="/propagandalive/video"> Video </a></li><li class="list-item l
ist-item-i"> <a href="/propagandalive/video/cartoon-di-makkox"> Makkox </a></li><li class="list-item list-item-i"> <a href="/grezzone/video"> reportage </a></li><li class="list-item list-item-i"> <a href="/
propagandalive/video/zerocalcare"> Zerocalcare </a></li><li class="list-item list-item-i"> <a href="/propagandalive/video/celenza"> celenza </a></li><li class="list-item list-item-i"> <a href="/propagandali
ve/video/social-top-ten"> Social Top-ten </a></li><li class="list-item list-item-i"> <a href="/propagandalive/video/musica-live"> Musica Live </a></li><li class="list-item list-item-i"> <a href="http://www.
la7.it/propagandalive/podcast"> Podcast </a></li></ul></div></div></div></div></div></div> <!-- FINE HEADER NEW --> <!-- MAIN CONTENT --><div id="main-wrapper" class="clearfix"><div id="main" class="clearfi
x"> <!-- HEADER PROPERTY --><div id="headerProperty" class="headerProperty" > <a href="/propagandalive"> </a><div class="region region-header-property"><div id="block-views-424cfe4f37463b0ace1f50117ceb1985"
 class="block block-views"><div class="content"><div class="view view-property-pages view-id-property_pages view-display-id-block_header_page view-dom-id-fd2af82810469664f5f8bec60448149a"><div class="view-c
ontent"><div class="views-row views-row-1 views-row-odd views-row-first views-row-last"><div class="image-bg lozad" data-background-image="https://www.la7.it/sites/default/files/property/header/page/propliv
e_page_0.jpg"></div></div></div></div></div></div><div id="block-views-property-new-block-1" class="block block-views"><div class="content"><div class="view view-property-new view-id-property_new view-displ
ay-id-block_1 view-dom-id-f0c2da60b008ababaf106db0e190daaa"><div class="view-content"><ul><li class="voce_menu"> <a href="/propagandalive/rivedila7" > Puntate </a></li><li class="voce_menu"> <a href="/propa
gandalive/video" > Video </a></li><li class="voce_menu"> <a href="https://www.la7.it/propagandalive/video/cartoon-di-makkox" > Makkox </a></li><li class="voce_menu"> <a href="/grezzone/video" > reportage </
a></li><li class="voce_menu"> <a href="/propagandalive/video/zerocalcare" > Zerocalcare </a></li><li class="voce_menu"> <a href="/propagandalive/video/celenza" > celenza </a></li><li class="voce_menu"> <a href="/propagandalive/video/social-top-ten" > Social Top-ten </a></li><li class="voce_menu"> <a href="/propagandalive/video/musica-live" > Musica Live </a></li><li class="voce_menu"> <a href="http://www.la7.it/propagandalive/podcast" > Podcast </a></li></ul></div></div></div></div></div></div> <!-- FINE HEADER PROPERTY --> <!-- FINE HEADER PROPERTY --> <!-- CONTENT - COLONNA RIGHT --><div class="main-content-node"> <!--<h1></h1> --><div class="tabs clearfix"></div><div class="content-video"><div class="region region-content"><div id="block-system-main" class="block block-system"><div class="content"><div class="contextProperty clearfix" itemscope itemtype="http://schema.org/NewsArticle"><meta itemscope itemprop="mainEntityOfPage" itemType="https://schema.org/WebPage" itemid="https://google.com/article"/><div id="node-la7_repliche" class="node node-la7-repliche node-full clearfix" ><div class="field field-name-field-upload-video field-type-field-kaltura-entryid field-label-hidden"><div class="field-items"><div class="field-item even"><div class="kaltura"><div class="kaltura-embed"><script type="application/ld+json" name="metaScript">{"@context": "https://schema.org","@type": "VideoObject","name": "Propaganda Live - Puntata del 21/10/2022","description": "Propaganda Live - Puntata del 21/10/2022","thumbnailUrl":  "https://kdam.iltrovatore.it/p/103/sp/10300/thumbnail/entry_id/0_4pcnv9t0/width/600/quality/100/name/0_4pcnv9t0.jpgname/0_4pcnv9t0.jpg_vrs8867","image": "//kdam.iltrovatore.it/p/103/sp/10300/thumbnail/entry_id/0_4pcnv9t0/width/600/quality/100/name/0_4pcnv9t0.jpgname/0_4pcnv9t0.jpg_vrs8867","duration": "PT03H03M11S","uploadDate": "2022-10-22T02:07:05+02:00","contentUrl":"https://awsvodpkg.iltrovatore.it/content/entry/data/0/532/0_4pcnv9t0_0_83wyd32f_1.mp4.urlset/master.m3u8
```
Abbiamo dovuto guardare la social top ten dal tablet ieri sera... @campipaolo hai tutta la mia gratitudine se ne esci fuori. ;-)

Grazie.

**Comment by nixxo** [comment]
trovato il problema e mandato un fix. Attendiamo @luivit

**Comment by campipaolo** [comment]
Grazie 1000!
Io attendo la nuova versione o qua su GitHub o nei repository kodi

**Comment by iltommi** [comment]
Grazie!

**Comment by puppinoo** [comment]
Grandissimi. Grazie.

**Comment by Testato** [comment]
> trovato il problema e mandato un fix. Attendiamo @luivit
> 
> per chi non volesse attendere: nel file `resources/lib/plugin.py`
> 
> aggiungere una virgola `,` alla `regex2` risultando così `regex2 = ',/content/(.*?).mp4'`

Ottimo, hai provato un po tutto? Anche ondemand ?
Domani provo anche io e se é tutto ok pubblico la nuova versione e aggiorno anche sul repo koso ufficiale

**Comment by campipaolo** [comment]
> > per chi non volesse attendere: nel file `resources/lib/plugin.py`
> > aggiungere una virgola `,` alla `regex2` risultando così `regex2 = ',/content/(.*?).mp4'`
> 
> Ottimo, hai provato un po tutto? Anche ondemand ? Domani provo anche io e se é tutto ok pubblico la nuova versione e aggiorno anche sul repo kodi ufficiale

La repo ufficiale è rimasta ferma alla 6.01 e su GitHub è attualmente 6.02
Quando aggiorni alla 6.03 torna tutto in pari, perfetto!

**Comment by Testato** [comment]
E si non avevo aggiornato sul repo kodi perché lo faccio solo per cambiamenti più importanti.
Oggi non ho avuto tempo spero domani di riuscire visto che devo sistemare altre piccole cose che ho in sospeso.
Pubblicherò la 6.1.0

**Comment by campipaolo** [comment]
> E si non avevo aggiornato sul repo kodi perché lo faccio solo per cambiamenti più importanti. Oggi non ho avuto tempo spero domani di riuscire visto che devo sistemare altre piccole cose che ho in sospeso. Pubblicherò la 6.1.0

Ok!
Attendiamo, è il minimo da parte di tutta la community

**Comment by marcocalm** [comment]
> trovato il problema e mandato un fix. Attendiamo @luivit
> 
> per chi non volesse attendere: nel file `resources/lib/plugin.py`
> 
> aggiungere una virgola `,` alla `regex2` risultando così `regex2 = ',/content/(.*?).mp4'`

Perfetto grazie, funziona di nuovo tutto!

**Comment by MarcoAlici** [comment]
> trovato il problema e mandato un fix. Attendiamo @luivit
> 
> per chi non volesse attendere: nel file `resources/lib/plugin.py`
> 
> aggiungere una virgola `,` alla `regex2` risultando così `regex2 = ',/content/(.*?).mp4'`

Funziona! 
Grazie!

**Comment by Testato** [comment]
@MarcoAlici 
Ho rilasciato la versione nuova con molti piu bug risolti, non fate manualmente questa cosa

**Comment by MarcoAlici** [comment]
> Ho rilasciato la versione nuova con molti piu bug risolti, non fate manualmente questa cosa

Ciao,
è già stato rilasciato? Le mie installazioni di Kodi non lo rilevano...

**Comment by campipaolo** [comment]
Non mi pare che nelle repository sia già presente
Io ho installato lo zip preso qua da GitHub

**Comment by Testato** [comment]
No non hanno ancora accettato la mia nuova versione
Installate la 6.1.0 scaricando lo zip
