### ISSUE TITLE
[FIXED] RivediLa7 non funziona più 

### ISSUE THREAD

**Issue by Maxwell-hash** [luivit/plugin.video.rivedila7#66]
Come da titolo. Probabile qualcosa sia cambiato nel sito di La7 riguardo alla procedura di streaming. Ritorna messaggio di errore.

Piccola correzione ora pare che la live funzioni e l'errore rimane solo su Rivedila7 . Aggiorno nel caso qualcosa cambi nei prossimi giorni

**Comment by Testato** [comment]
Ieri ho pubblicato nuova versione 6.1.1
Installa e vedi come va.

Ho anche spedito nuova versione al repo kodi quindi fra poco si aggiornerà in automatico a tutti

**Comment by Maxwell-hash** [comment]
Ah perfetto. Grazie

**Comment by Maxwell-hash** [comment]
> Ieri ho pubblicato nuova versione 6.1.1 Installa e vedi come va. Basta scaricare da qui il .zip e installare appunto su kodi via .zip
> 
> Ho anche spedito nuova versione al repo kodi quindi fra poco si aggiornerà in automatico a tutti

Risolto . Funziona ora

**Comment by lorenzos** [comment]
> Ieri ho pubblicato nuova versione 6.1.1 Installa e vedi come va. Basta scaricare da qui il .zip

Scusa, io vedo ancora la 6.1.0 ad ora (commit di 12 ore fa), ed installandola da ZIP continuo ad avere errori con RivediLa7.

**Comment by Testato** [comment]
@lorenzos 
Essendo un aggiornamento corposo va chiuso e riavviato kodi, se nemmeno funziona serve disinstallare il plugin e reinstallarlo.

**Comment by lorenzos** [comment]
@Testato Grazie per la risposta. Ho riavviato ed ora funziona 👍

**Comment by Testato** [comment]
No, l'ho deprecata da anni.
Non ha più senso non passare alla 19 visto che si sta lavorando alla 20
