### ISSUE TITLE
smesso di funzionare

### ISSUE THREAD

**Issue by valonqar** [luivit/plugin.video.rivedila7#67]
Ciao! ho usato il plugin regolarmente per anni, ma dopo l'ultimo aggiornamento non ne vuole sapere di funzionare. Ho disinstallato Kodi, reinstallato l'app sulla mia Firestick, reinstallato il plugin ma niente.

**Comment by Testato** [comment]
Sarà un problema particolare tuo.
Priva ad esempio su un telefono Android vedrai che funziona

**Comment by valonqar** [comment]
Ho provato sia da telefono, sia da pc Windows. Continua a darmi sempre lo stesso errore.
Allego il log dell'errore.

<a href="https://ibb.co/cyhpY9P"><img src="https://i.ibb.co/hgFnYNk/Immagine-2022-11-05-171542.png" alt="Immagine-2022-11-05-171542" border="0"></a>

**Comment by valonqar** [comment]
Il problema si presenta su Firestick, sul mio cellulare Android e sul mio pc Windows 11.

**Comment by Testato** [comment]
Ma mica hai dimenticato di installare l'ultima versione via .zip scaricandola da qui ? 😅

**Comment by valonqar** [comment]
Hai ragione. Mea culpa. Pensavo che sul repository fosse aggiornato. Grazie mille del support!

**Comment by Testato** [comment]
Ho postato la PR verso il repo Kodi, ma impiegano diversi giorni prima di verificarla e accettarla, quindi in attesa si deve scaricare da qui il .zip e installarlo manualmente.
