### ISSUE TITLE
Could you please update PR #4144 to get it merged?

### ISSUE THREAD

**Issue by derkling** [luivit/plugin.video.rivedila7#69]
Can we please update [PR  #4144](https://github.com/xbmc/repo-plugins/pull/4144) as requested by the reviewer, i.e. by removing the `.gitignore` file, so that it gets merged and we can get the La7 plugin working again?

If you have not time to follow up on this, I'm happy to jump in and send a new PR with the required updates.

**Comment by Testato** [comment]
Lo fo io oggi

**Comment by Testato** [comment]
I tipi di kodi sono lentissimi, gli ho fatto una domanda e ancora non hanno risposto :-)

Lo zip lo scarichi da qui https://github.com/luivit/plugin.video.rivedila7/archive/refs/heads/master.zip

**Comment by Testato** [comment]
dopo 3 mesi ed una bella ramanzina si sono decisi a mergiare :-)
