### ISSUE TITLE
La7d

### ISSUE THREAD

**Issue by Testato** [luivit/plugin.video.rivedila7#7]
Il sito ora propone anche i programmi La7d, il Live Streaming al momento non esiste, ma ci sono le altre due categorie:
- La7d Replay
http://www.la7.it/rivedila7/2/LA7D

- La7d On-Demand
http://www.la7.it/cambio-cuoco/rivedila7/archivio

Si deve capire se esiste un elenco con tutti i programmi di La7d, perché in quello generico non ci sono questi programmi, cioè qui http://www.la7.it/tutti-i-programmi che credo sia l'indirizzo a cui punta il plugin non contiene ad esempio cambio-cuoco

**Comment by luivit** [comment]
Nella lista dei programmi degli ultimi 7 giorni pochissimi sono disponibili. Quindi non credo si sentirà la mancanza :p
Per la parte On-Demand idem, fa vedere solo alcune poche cose e neanche tutte le puntate

**Comment by Testato** [comment]
Si concordo, l'ho segnalato per averlo come ToDo :-)
La gestione di La7D anche se con pochi contenuti da parte del provider sarà comunque una funzionalità importante per il plugin sotto l'aspetto del marketing ;-)
