### ISSUE TITLE
la 7 in ritardo

### ISSUE THREAD

**Issue by ninuxi** [luivit/plugin.video.rivedila7#71]
ciao
da un paio di giorni la 7 su kodi con il tuo add ons si vede in ritardo di qualche ora

**Comment by bitbooster** [comment]
Ho notato anch'io lo stesso. Sia la7 live che la7d live.
All'avvio sono 4:24:00 in ritardo, con si può vedere chiamando l'info screen.
Come 'workaround' è possibile avanzare con la funzione di Forward le 4 e passa ore e tornare a vedere in diretta (anzi ho notato che a quel punto è addirittura una manciata di secondi in anticipo su la7 vista via web da tablet android)

**Comment by Testato** [comment]
Che storia,
Confermo il bug
Appena ho un attimo ci guardo

**Comment by lorenzos** [comment]
Non so se sia una coincidenza, ma a me ha cominciato a fare così ieri dopo l'aggiornamento del DRM di WineDevine (o come si chiama).

Parte quattro ore indietro, però è facile avanzare fino alla fine (anche perché, a differenza dei normali video, il playback non si interrompe se per sbaglio si avanza "oltre la fine").

Inoltre adesso se c'è bisogno di mettere in pausa o rivedere qualche momento della live, si riesce a farlo senza rischiare che lo stream si interrompa. Prima era un po' un azzardo, spesso la pausa o il riavvolgimento facevano saltare lo stream (se non subito, dopo qualche minuto).

Insomma, it's not a bug, it's a feature. Spero che possa essere risolta la questione dell'avvio in ritardo senza perdere i vantaggi sopra descritti 😅

**Comment by Testato** [comment]
Ottima osservazione, si può provare a usare una vecchia widevine per avere conferma della cosa, ma non so se si trova in giro e come si installa poi manualmente

**Comment by lorenzos** [comment]
Inputstream-helper tiene un backup della penultima versione di Widevine installato, è possibile fare il fallback semplicemente da UI. Se mi ricordo domani faccio una prova. Magari è solo un caso eh, e quelli di La7 han veramente cambiato qualcosa nel formato dello streaming, vedremo...

**Comment by bitbooster** [comment]
> Non so se sia una coincidenza, ma a me ha cominciato a fare così ieri dopo l'aggiornamento del DRM di Widevine.
> 
Hmm... vero. In effetti nel mio caso forse il giorno prima avevo finalmente accettato il prompt di aggiornamento di Widevine.
A questo punto magari dare un'occhiata al changelog di Widevine potrebbe anche suggerire il motivo del cambio di comportamento.

**Comment by Testato** [comment]
Widevine è closed source, non c'e' un suo repo online

**Comment by lorenzos** [comment]
Mmmh, come non detto. Ho ripristinato un paio di backup di Widevine che InputStream Helper tiene automaticamente, direttamente con la sua UI (verificando sia con le informazioni do versione che lui stesso dà, sia verificando la data della libreria direttamente via SSH), e lo stream parte sempre con quelle 4 ore e mezza di buffer... Direi abbiano modificato qualcosa lato La7.

**Comment by lorenzos** [comment]
Per quel che vale, il comando `PlayerOpen` può essere usato per fare in modo che lo stream parta dalla fine. Io avvio la diretta spesso da remoto, chiamando la URL `http://192.168.1.xxx/jsonrpc`, e oggi ho verificato che con questo payload parte dalla fine senza problemi:

```
{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "Player.Open",
  "params": {
    "options": {
      "resume": 100
    },
    "item": {
      "file": "plugin://plugin.video.rivedila7/?mode=diretta_la7&_l=.pvr"
    }
  }
}
```

Magari si riesce ad usare lo stesso parametro dal tuo codice Python?

**Comment by Testato** [comment]
Risolto, 
hanno implementato il Presentation Delay, cosa che era partita molto tempo fa da una mia richiesta :-)

Installate la nuova versione, ora faccio anche il push verso il repo kodi
Ora parte dalla fine e si puo' tranquillamente poi andare indietro di 4 ore
