### ISSUE TITLE
Precedente Pagina

### ISSUE THREAD

**Issue by Testato** [luivit/plugin.video.rivedila7#9]
Nella funzionalità "Tutti i programmi" a fine elenco appare Prossima pagina e Precedente pagina.
Mentre Prossima pagina è fondamentale, invece Precedente pagina incasina le cose.
Essendoci già di default la funzione di tornare indietro, i due puntini in cima .., quando si usa Precedente pagina e poi magari i puntini si entra in un loop da cui per iscire si deve cliccare tante volte.
Perché i due puntini standard vanno indietro di un livello mentre Precedente pagina va indietro nella History del documento.

Imho la cosa migliore è semplicemente eliminare Precedente pagina, l'utente Kodi è da sempre abituato ai due puntini .. per andare indietro.

**Comment by luivit** [comment]
concordo, rimosso.
